#lang racket/base

;; @generated by codegen (python3 -m codegen); DO NOT EDIT.
;; Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).
;;
;; The UNSTABLE generated surface: thin uncontracted wrappers over
;; the raw layer. Names and signatures track the allowlist;
;; promotion into the contracted public facade (torch/foreign.rkt)
;; is hand-curated.

(require (only-in ffi/vector list->s64vector)
         (only-in "foreign/error.rkt" check-handle)
         (only-in "foreign/structs.rkt" wrap-tensor)
         (only-in "foreign/generated/linalg.rkt"
                  tr-gen-dot/raw
                  tr-gen-matmul/raw
                  tr-gen-mm/raw
                  tr-gen-mv/raw)
         (only-in "foreign/generated/shape.rkt"
                  tr-gen-cat/raw
                  tr-gen-reshape/raw))

(provide cat
         dot
         matmul
         mm
         mv
         reshape)

(define (cat tensors dim)
  (wrap-tensor
   (check-handle 'cat (tr-gen-cat/raw tensors (length tensors) dim))))

(define (dot self tensor)
  (wrap-tensor
   (check-handle 'dot (tr-gen-dot/raw self tensor))))

(define (matmul self other)
  (wrap-tensor
   (check-handle 'matmul (tr-gen-matmul/raw self other))))

(define (mm self mat2)
  (wrap-tensor
   (check-handle 'mm (tr-gen-mm/raw self mat2))))

(define (mv self vec)
  (wrap-tensor
   (check-handle 'mv (tr-gen-mv/raw self vec))))

(define (reshape self shape)
  (wrap-tensor
   (check-handle 'reshape (tr-gen-reshape/raw self (list->s64vector shape) (length shape)))))
