#lang racket/base

;; @generated by codegen (python3 -m codegen); DO NOT EDIT.
;; Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).
;;
;; The UNSTABLE generated surface. One define-generated-op form per
;; allowlist entry; the macro expands each into the raw FFI binding
;; and a thin uncontracted wrapper. Promotion into the contracted
;; public facade (torch/foreign.rkt) is hand-curated.

(require (only-in "foreign/define-generated.rkt"
                  define-generated-op))

(provide cat
         dot
         matmul
         mm
         mv
         reshape)

(define-generated-op cat tr_gen_cat
  ([tensors tensor-list] [dim int64]))

(define-generated-op dot tr_gen_dot
  ([self tensor] [tensor tensor]))

(define-generated-op matmul tr_gen_matmul
  ([self tensor] [other tensor]))

(define-generated-op mm tr_gen_mm
  ([self tensor] [mat2 tensor]))

(define-generated-op mv tr_gen_mv
  ([self tensor] [vec tensor]))

(define-generated-op reshape tr_gen_reshape
  ([self tensor] [shape int-array]))
