"""Emit the extern "C" shim shards (headers + sources + sources.cmake)."""

from __future__ import annotations

from .ir import (
    BOOL,
    DOUBLE,
    INT64,
    INT_ARRAY,
    OPTIONAL_DTYPE,
    OPTIONAL_INT64,
    OPTIONAL_INT_ARRAY,
    OPTIONAL_TENSOR,
    SCALAR,
    TENSOR,
    TENSOR_LIST,
    Op,
    Param,
)

BANNER = (
    "// @generated by codegen (python3 -m codegen); DO NOT EDIT.\n"
    "// Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).\n"
)

_C_DECLS = {
    TENSOR: "const tr_tensor* {n}",
    OPTIONAL_TENSOR: "const tr_tensor* {n}",  # NULL == c10::nullopt
    SCALAR: "double {n}",
    DOUBLE: "double {n}",
    INT64: "int64_t {n}",
    BOOL: "bool {n}",
    INT_ARRAY: "const int64_t* {n}, int64_t {n}_len",
    TENSOR_LIST: "const tr_tensor* const* {n}, int64_t {n}_len",
    # Optionals carry a presence flag (or a -1 sentinel for dtype) so the
    # Racket side never has to pass a NULL pointer for a value type.
    OPTIONAL_INT64: "int64_t {n}, bool {n}_has",
    OPTIONAL_INT_ARRAY: "const int64_t* {n}, int64_t {n}_len, bool {n}_has",
    OPTIONAL_DTYPE: "int32_t {n}",  # -1 == c10::nullopt
}

# Kinds whose C decl mentions `bool`, so the header needs <stdbool.h>.
_BOOL_DECL_KINDS = frozenset({BOOL, OPTIONAL_INT64, OPTIONAL_INT_ARRAY})


def _c_decl(p: Param, *, receiver: bool) -> str:
    # An in-place op's receiver is the mutable `self` handle.
    if receiver:
        return f"tr_tensor* {p.name}"
    return _C_DECLS[p.kind].format(n=p.name)


def _c_params(op: Op) -> str:
    return ", ".join(
        _c_decl(p, receiver=(op.inplace and i == 0))
        for i, p in enumerate(op.params)
    )


def _arg_expr(p: Param) -> str:
    if p.kind == TENSOR:
        return f"{p.name}->value"
    if p.kind == OPTIONAL_TENSOR:
        return (f"{p.name} ? c10::optional<at::Tensor>({p.name}->value) "
                f": c10::optional<at::Tensor>()")
    if p.kind == INT_ARRAY:
        return (f"at::IntArrayRef({p.name}, "
                f"static_cast<size_t>({p.name}_len))")
    if p.kind == TENSOR_LIST:
        return f"{p.name}_vec"
    if p.kind == OPTIONAL_INT64:
        return (f"{p.name}_has ? c10::optional<int64_t>({p.name}) "
                f": c10::optional<int64_t>()")
    if p.kind == OPTIONAL_INT_ARRAY:
        return (f"{p.name}_has ? c10::optional<at::IntArrayRef>("
                f"at::IntArrayRef({p.name}, "
                f"static_cast<size_t>({p.name}_len))) "
                f": c10::optional<at::IntArrayRef>()")
    if p.kind == OPTIONAL_DTYPE:
        return (f"{p.name} < 0 ? c10::optional<at::ScalarType>() "
                f": c10::optional<at::ScalarType>("
                f"static_cast<at::ScalarType>({p.name}))")
    return p.name


def emit_header(shard: str, ops: list[Op]) -> str:
    needs_bool = any(p.kind in _BOOL_DECL_KINDS for op in ops for p in op.params)
    lines = [BANNER, "#pragma once", ""]
    if needs_bool:
        lines += ["#include <stdbool.h>", ""]
    lines += ['#include "torchrkt/c_api/tensor.h"', ""]
    lines += ["#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    lines += [
        "/* Generated ops ({}). A functional op returns a new tr_tensor".format(
            shard
        ),
        " * handle (NULL on error); an in-place op mutates its first handle",
        " * and returns an int status (0 ok, 1 with tr_last_error set). */",
        "",
    ]
    for op in ops:
        ret = "int" if op.inplace else "tr_tensor*"
        lines.append(f"{ret} {op.c_name}({_c_params(op)});")
    lines += ["", "#ifdef __cplusplus", "}", "#endif"]
    return "\n".join(lines) + "\n"


def emit_umbrella(shards: list[str]) -> str:
    lines = [BANNER, "#pragma once", ""]
    for shard in shards:
        lines.append(f'#include "torchrkt/c_api/generated/{shard}.h"')
    return "\n".join(lines) + "\n"


def _emit_body(op: Op) -> list[str]:
    # OPTIONAL_TENSOR is intentionally absent: a NULL handle is the valid
    # c10::nullopt encoding, so it is not null-guarded.
    guards = []
    for p in op.params:
        if p.kind in (TENSOR, INT_ARRAY, TENSOR_LIST):
            guards.append(f"!{p.name}")
        if p.kind in (INT_ARRAY, TENSOR_LIST):
            guards.append(f"{p.name}_len < 0")
    ret_type = "int" if op.inplace else "tr_tensor*"
    lines = [f"{ret_type} {op.c_name}({_c_params(op)}) {{"]
    if guards:
        cond = " || ".join(guards)
        fail = "null_arg_status" if op.inplace else "null_arg"
        lines += [
            f"  if ({cond}) {{",
            f'    return torchrkt::{fail}("{op.c_name}");',
            "  }",
        ]
    preamble = []
    for p in op.params:
        if p.kind == TENSOR_LIST:
            preamble += [
                f"    std::vector<at::Tensor> {p.name}_vec;",
                f"    {p.name}_vec.reserve("
                f"static_cast<size_t>({p.name}_len));",
                f"    for (int64_t i = 0; i < {p.name}_len; ++i) {{",
                f"      if (!{p.name}[i]) {{",
                "        throw std::invalid_argument("
                f'"null tensor in {p.name}");',
                "      }",
                f"      {p.name}_vec.push_back({p.name}[i]->value);",
                "    }",
            ]
    if op.inplace:
        # self->value.<base>_(<rest>); mutates in place, returns status.
        recv = op.params[0].name
        method_args = ", ".join(_arg_expr(p) for p in op.params[1:])
        lines += [f'  return torchrkt::status_call("{op.c_name}", [&] {{']
        lines += preamble
        lines += [f"    {recv}->value.{op.base}_({method_args});",
                  "  });", "}"]
    else:
        call = f"at::{op.base}({', '.join(_arg_expr(p) for p in op.params)})"
        lines += [f'  return torchrkt::alloc_result("{op.c_name}", [&] {{']
        lines += preamble
        lines += [f"    return {call};", "  });", "}"]
    return lines


def emit_source(shard: str, ops: list[Op]) -> str:
    needs_vector = any(
        p.kind == TENSOR_LIST for op in ops for p in op.params
    )
    lines = [BANNER, f'#include "torchrkt/c_api/generated/{shard}.h"', ""]
    lines += ["#include <torch/torch.h>", ""]
    if needs_vector:
        lines += ["#include <stdexcept>", "#include <vector>", ""]
    lines += [
        '#include "torchrkt/detail/op_call.hpp"',
        '#include "torchrkt/detail/tensor_handle.hpp"',
        "",
        'extern "C" {',
        "",
    ]
    for op in ops:
        lines += _emit_body(op)
        lines.append("")
    lines += ['}  // extern "C"']
    return "\n".join(lines) + "\n"


def emit_sources_cmake(shards: list[str]) -> str:
    lines = [
        "# @generated by codegen (python3 -m codegen); DO NOT EDIT.",
        "target_sources(torchrkt",
        "  PRIVATE",
    ]
    for shard in shards:
        lines.append(
            "    ${CMAKE_CURRENT_SOURCE_DIR}/src/torchrkt/generated/"
            f"{shard}.cpp"
        )
    lines += [")"]
    return "\n".join(lines) + "\n"
