"""Emit the Racket layer: torch/generated.rkt (compact define-generated-op
forms — the macro in torch/foreign/define-generated.rkt owns the actual
expansion into raw FFI binding + wrapper) and the parity manifest."""

from __future__ import annotations

from .ir import Op

BANNER = (
    ";; @generated by codegen (python3 -m codegen); DO NOT EDIT.\n"
    ";; Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).\n"
)


def _rkt_arg(name: str) -> str:
    return name.replace("_", "-")


def emit_wrappers(shards: dict[str, list[Op]]) -> str:
    all_ops = sorted(
        (op for ops in shards.values() for op in ops),
        key=lambda o: o.racket_name,
    )
    lines = ["#lang racket/base", "", BANNER.rstrip()]
    lines += [
        ";;",
        ";; The UNSTABLE generated surface. One define-generated-op form per",
        ";; allowlist entry; the macro expands each into the raw FFI binding",
        ";; and a thin uncontracted wrapper. Promotion into the contracted",
        ";; public facade (torch/foreign.rkt) is hand-curated.",
        "",
        '(require (only-in "foreign/define-generated.rkt"',
        "                  define-generated-op))",
        "",
    ]
    provides = [op.racket_name for op in all_ops]
    lines.append("(provide " + "\n         ".join(provides) + ")")
    for op in all_ops:
        args = " ".join(
            f"[{_rkt_arg(p.name)} {p.kind}]" for p in op.params
        )
        lines += [
            "",
            f"(define-generated-op {op.racket_name} {op.c_name}",
            f"  ({args}))",
        ]
    return "\n".join(lines) + "\n"


def emit_manifest(shards: dict[str, list[Op]]) -> str:
    all_ops = sorted(
        (op for ops in shards.values() for op in ops),
        key=lambda o: o.racket_name,
    )
    lines = [BANNER.rstrip()]
    lines += [
        ";; Parity manifest: (racket-name python-attr (arg kinds ...)).",
        ";; Consumed by torch/tests/python-cross-test.rkt.",
        "(",
    ]
    for op in all_ops:
        kinds = " ".join(p.kind for p in op.params)
        lines.append(f' ({op.racket_name} "{op.python_name}" ({kinds}))')
    lines.append(")")
    return "\n".join(lines) + "\n"
