"""Emit the Racket layers: raw FFI shards, the unstable wrapper surface
(torch/generated.rkt), and the parity manifest for the cross-test."""

from __future__ import annotations

from .ir import BOOL, DOUBLE, INT64, INT_ARRAY, SCALAR, TENSOR, TENSOR_LIST, Op

BANNER = (
    ";; @generated by codegen (python3 -m codegen); DO NOT EDIT.\n"
    ";; Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).\n"
)

_SCALAR_CTYPES = {SCALAR: "_double", DOUBLE: "_double", INT64: "_int64",
                  BOOL: "_stdbool"}


def _rkt_arg(name: str) -> str:
    return name.replace("_", "-")


def _fun_params(op: Op) -> list[str]:
    out = []
    for p in op.params:
        n = _rkt_arg(p.name)
        if p.kind == TENSOR:
            out.append(f"({n} : _Tensor)")
        elif p.kind == INT_ARRAY:
            out.append(f"({n} : (_s64vector i))")
            out.append(f"({n}-len : _int64)")
        elif p.kind == TENSOR_LIST:
            out.append(f"({n} : (_list i _Tensor))")
            out.append(f"({n}-len : _int64)")
        else:
            out.append(f"({n} : {_SCALAR_CTYPES[p.kind]})")
    return out


def _ffi_unsafe_imports(ops: list[Op]) -> list[str]:
    kinds = {p.kind for op in ops for p in op.params}
    names = {"_fun"}
    for kind in kinds:
        if kind in _SCALAR_CTYPES:
            names.add(_SCALAR_CTYPES[kind])
    if INT_ARRAY in kinds or TENSOR_LIST in kinds:
        names.add("_int64")
    if TENSOR_LIST in kinds:
        names.add("_list")
    return sorted(names)


def emit_raw_shard(shard: str, ops: list[Op]) -> str:
    kinds = {p.kind for op in ops for p in op.params}
    requires = [
        "(only-in ffi/unsafe {})".format(" ".join(_ffi_unsafe_imports(ops))),
        "(only-in ffi/unsafe/alloc allocator)",
    ]
    if INT_ARRAY in kinds:
        requires.append("(only-in ffi/vector _s64vector)")
    requires.append(
        '(only-in "../syntax.rkt" _Tensor _Tensor/null'
        " define-torch tr-tensor-free/raw)"
    )
    lines = ["#lang racket/base", "", BANNER.rstrip()]
    lines += [
        f";; Raw bindings for generated ops (c_api/generated/{shard}.h).",
        "",
    ]
    lines.append("(require " + "\n         ".join(requires) + ")")
    lines.append("")
    provides = sorted(op.racket_raw for op in ops)
    lines.append(
        "(provide " + "\n         ".join(provides) + ")"
    )
    for op in sorted(ops, key=lambda o: o.racket_raw):
        lines += [
            "",
            f"(define-torch {op.racket_raw}",
            "  (_fun {} -> _Tensor/null)".format(" ".join(_fun_params(op))),
            f"  #:c-id {op.c_name}",
            "  #:wrap (allocator tr-tensor-free/raw))",
        ]
    return "\n".join(lines) + "\n"


def _wrapper_args(op: Op) -> tuple[list[str], list[str]]:
    """Returns (lambda params, raw-call argument expressions)."""
    params, args = [], []
    for p in op.params:
        n = _rkt_arg(p.name)
        params.append(n)
        if p.kind == INT_ARRAY:
            args += [f"(list->s64vector {n})", f"(length {n})"]
        elif p.kind == TENSOR_LIST:
            args += [n, f"(length {n})"]
        else:
            args.append(n)
    return params, args


def emit_wrappers(shards: dict[str, list[Op]]) -> str:
    all_ops = [op for ops in shards.values() for op in ops]
    kinds = {p.kind for op in all_ops for p in op.params}
    requires = []
    if INT_ARRAY in kinds:
        requires.append("(only-in ffi/vector list->s64vector)")
    requires.append('(only-in "foreign/error.rkt" check-handle)')
    requires.append('(only-in "foreign/structs.rkt" wrap-tensor)')
    for shard in sorted(shards):
        names = sorted(op.racket_raw for op in shards[shard])
        requires.append(
            f'(only-in "foreign/raw/generated/{shard}.rkt"\n'
            + "\n".join(f"                  {n}" for n in names)
            + ")"
        )
    lines = ["#lang racket/base", "", BANNER.rstrip()]
    lines += [
        ";;",
        ";; The UNSTABLE generated surface: thin uncontracted wrappers over",
        ";; the raw layer. Names and signatures track the allowlist;",
        ";; promotion into the contracted public facade (torch/foreign.rkt)",
        ";; is hand-curated.",
        "",
    ]
    lines.append("(require " + "\n         ".join(requires) + ")")
    lines.append("")
    provides = sorted(op.racket_name for op in all_ops)
    lines.append("(provide " + "\n         ".join(provides) + ")")
    for op in sorted(all_ops, key=lambda o: o.racket_name):
        params, args = _wrapper_args(op)
        head = f"(define ({op.racket_name} {' '.join(params)})"
        call = f"({op.racket_raw} {' '.join(args)})"
        lines += [
            "",
            head,
            "  (wrap-tensor",
            f"   (check-handle '{op.racket_name} {call})))",
        ]
    return "\n".join(lines) + "\n"


def emit_manifest(shards: dict[str, list[Op]]) -> str:
    all_ops = sorted(
        (op for ops in shards.values() for op in ops),
        key=lambda o: o.racket_name,
    )
    lines = [BANNER.rstrip()]
    lines += [
        ";; Parity manifest: (racket-name python-attr (arg kinds ...)).",
        ";; Consumed by torch/tests/python-cross-test.rkt.",
        "(",
    ]
    for op in all_ops:
        kinds = " ".join(p.kind for p in op.params)
        lines.append(f' ({op.racket_name} "{op.python_name}" ({kinds}))')
    lines.append(")")
    return "\n".join(lines) + "\n"
