(require torch torch/nn)
(define dev (accelerator-if-available))
(printf "device: ~a\n" dev)
(define net
  (with-default-device dev
    (sequential (linear 256 512) (relu) (linear 512 512) (relu) (linear 512 10))))
(define opt (adam (parameters net) #:lr 0.001))
(with-default-device dev
  (for ([step (in-range 400)])
    (define x (randn 64 256))
    (define y (randn 64 10))
    (zero-grads! opt)
    (define loss (mse-loss (net x) y))
    (backward! loss)
    (step! opt)
    (when (zero? (modulo step 100)) (printf "step ~a loss ~a\n" step (item loss)))))
(with-default-device dev (randn 1200 1200))
(with-default-device dev (for ([_ (in-range 3000)]) (void (matmul (randn 256 256) (randn 256 256)))))
(with-default-device dev (randn 900 900))
(finalizer-failures)
(native-memory-use)
