#lang racket/base
(require torch)
(define x (reshape (tensor '(1.0 3.0 5.0 7.0)) 1 2 1 2))
(define m (zeros 2))
(define v (ones 2))
(define (try label thunk)
  (with-handlers ([exn:fail? (lambda (e)
                               (printf "~a => ~a\n" label
                                       (car (regexp-split #rx"\n" (exn-message e)))))])
    (thunk)
    (printf "~a => OK\n" label)))
(try "training #t, no stats   " (lambda () (batch-norm x #:training? #t)))
(try "training #t, both stats " (lambda () (batch-norm x #:training? #t #:running-mean m #:running-var v)))
(try "training #t, only mean  " (lambda () (batch-norm x #:training? #t #:running-mean m)))
(try "training #f explicit, no stats" (lambda () (batch-norm x #:training? #f)))
(try "training absent, no stats    " (lambda () (batch-norm x)))
(try "training #f explicit, stats   " (lambda () (batch-norm x #:training? #f #:running-mean m #:running-var v)))
