#lang racket/base
(require torch)
(define n (tensor 0))
(displayln (list 'tensor-0 (tensor-dtype n) (tensor-shape n)))
(define m (add n 1))
(displayln (list 'add-int (tensor-dtype m) (item m)))
(define b (to-dtype (zeros 1) 'int64))
(displayln (list 'zeros-int64-add (tensor-dtype (add b 1)) (item (add b 1))))
(displayln (list 'zeros-0dim (with-handlers ([exn:fail? exn-message]) (tensor-shape (zeros)))))
(define mask (reshape (ne (tensor '(1 0)) 0) 2 1))
(displayln (list 'where (tensor->list (where mask (ones 2 3) (zeros 2 3)))))
(define y (ones 2 2 4 4))
(define padded (zeros 2 2 6 6))
(copy! (narrow (narrow padded 2 1 4) 3 1 4) y)
(displayln (list 'narrow-copy!-writes-through (item (sum padded))))
(displayln (list 'draw-seed (draw-seed) (draw-seed #:generator (make-generator 3))))
