#lang racket/base

(module+ test
  (require (only-in racket/file make-temporary-file)
           rackunit
           (only-in syntax/macro-testing convert-compile-time-error)
           "../main.rkt"
           "../nn.rkt")

  (define-layer Kinds (n w b shift child absent)
    #:init (n)
    (set! w (Parameter (ones 2)))
    (set! b (Parameter (zeros 2)))
    (set! shift (Buffer (ones 2)))
    (set! child (Linear 2 2))
    #:forward (x)
    (list n w b shift child absent))

  (test-case "fields are classified by value at construction"
    (manual-seed! 0)
    (define k (Kinds 7))
    (check-equal? (map car (named-parameters k))
                  '("w" "b" "child.weight" "child.bias"))
    (check-true (andmap requires-grad? (parameters k)))
    (check-equal? (map tensor-shape (buffers k)) '((2)))
    (check-equal? (map car (named-children k)) '("child"))
    (check-true (linear? (car (children k))))
    (define seen (k (ones 2)))
    (check-equal? (car seen) 7 "a plain field is kept, not registered")
    (check-false (list-ref seen 5) "a field never assigned is #f"))

  (test-case "buffers are named, listed after parameters, and round-trip the state dict"
    (define k (Kinds 1))
    (check-equal? (map car (named-buffers k)) '("shift"))
    (check-equal? (map car (state-dict k))
                  '("w" "b" "child.weight" "child.bias" "shift"))
    (define-layer Outer (inner)
      #:init ()
      (set! inner (Kinds 1))
      #:forward (x) x)
    (check-equal? (map car (named-buffers (Outer))) '("inner.shift"))
    (define-layer Stats (fc mean)
      #:init (v)
      (set! fc (Linear 1 1))
      (set! mean (Buffer (full v 2)))
      #:forward (x) x)
    (define path (make-temporary-file "rkt-buf-~a.safetensors"))
    (manual-seed! 1)
    (define saved (Stats 7.0))
    (save-state! saved path)
    (manual-seed! 2)
    (define loaded (Stats 1.0))
    (check-equal? (tensor->list (car (buffers loaded))) '(1.0 1.0))
    (load-state! loaded path)
    (check-equal? (map car (state-dict loaded)) '("fc.weight" "fc.bias" "mean"))
    (check-equal? (tensor->list (car (buffers loaded))) '(7.0 7.0))
    (check-equal? (map tensor->list (parameters loaded))
                  (map tensor->list (parameters saved)))
    (delete-file path)
    (define-layer Typed (mask count)
      #:init (n)
      (set! mask (Buffer (eq (tril (ones 2 2)) 0)))
      (set! count (Buffer (tensor (list n 3))))
      #:forward (x) x)
    (define typed-path (make-temporary-file "rkt-typed-~a.safetensors"))
    (save-state! (Typed 16777217) typed-path)
    (define typed (Typed 0))
    (load-state! typed typed-path)
    (check-equal? (map tensor-dtype (buffers typed)) '(bool int64))
    (check-equal? (tensor->list (car (buffers typed))) '(0.0 1.0 0.0 0.0))
    (check-equal? (tensor->list (cadr (buffers typed))) '(16777217 3))
    (delete-file typed-path)
    (define-layer Wide (w)
      #:init ()
      (set! w (Buffer (to-dtype (ones 1) 'float64)))
      #:forward (x) x)
    (check-exn #rx"^save-state!: unsupported dtype"
               (lambda () (save-state! (Wide) typed-path))))

  (test-case "every child field registers, in declaration order, whatever its kind"
    (manual-seed! 0)
    (define-layer Inner (w)
      #:init ()
      (set! w (Parameter (ones 3)))
      #:forward (x) x)
    (define-layer Many (a b c d e)
      #:init ()
      (set! a (Linear 2 2))
      (set! b (Dropout))
      (set! c (Sequential (Linear 2 2) (LayerNorm 2)))
      (set! d (Inner))
      (set! e (LayerList (list (Embedding 4 2))))
      #:forward (x) x)
    (define m (Many))
    (check-equal? (map car (named-children m)) '("a" "b" "c" "d" "e"))
    (check-equal? (map car (named-parameters m))
                  '("a.weight" "a.bias"
                    "c.0.weight" "c.0.bias" "c.1.weight" "c.1.bias"
                    "d.w"
                    "e.0.weight"))
    (check-equal? (named-parameters m)
                  (apply append
                         (for/list ([c (in-list (named-children m))])
                           (named-parameters (cdr c)
                                             (string-append (car c) ".")))))
    (check-equal? (length (parameters m)) 8)
    (check-equal? (length (children m)) 5))

  (test-case "two parameters flattening to one name is an error"
    (define-layer Clash (p q)
      #:init ()
      (set! p (children-by-key (list (cons "x" (Linear 1 1)))))
      (set! q (children-by-key (list (cons "x" (Linear 1 1)))))
      #:forward (v) v)
    (check-exn #rx"^Clash: two children would share a name"
               (lambda () (Clash)))
    (define-layer Quiet (p q)
      #:init ()
      (set! p (children-by-key (list (cons "x" (Dropout)))))
      (set! q (children-by-key (list (cons "x" (Dropout)))))
      #:forward (v) v)
    (check-exn #rx"^Quiet: two children would share a name.*\"x\""
               (lambda () (Quiet)))
    (define-layer Spliced (head tail)
      #:init ()
      (set! head (children-by-index (list (Linear 1 1) (Dropout))))
      (set! tail (children-by-key (list (cons "out" (Linear 1 1)))))
      #:forward (v) v)
    (check-equal? (map car (named-children (Spliced))) '("0" "1" "out"))
    (check-equal? (map car (named-parameters (Spliced)))
                  '("0.weight" "0.bias" "out.weight" "out.bias"))
    (struct Twice ()
      #:methods gen:layer
      [(define (layer-named-parameters self prefix)
         (list (cons (string-append prefix "w") (ones 1))
               (cons (string-append prefix "w") (ones 1))))])
    (check-exn #rx"^LayerList: two parameters would share a name.*0[.]w"
               (lambda () (LayerList (list (Twice)))))
    (struct Overlap ()
      #:methods gen:layer
      [(define (layer-named-parameters self prefix)
         (list (cons (string-append prefix "x") (ones 1))))
       (define (layer-named-buffers self prefix)
         (list (cons (string-append prefix "x") (ones 1))))])
    (check-exn #rx"^LayerList: two state-dict entries would share a name.*0[.]x"
               (lambda () (LayerList (list (Overlap)))))
    (check-exn #rx"^LayerHash: contract violation"
               (lambda () (LayerHash (list (cons "" (Linear 1 1))))))
    (check-equal? (map car (named-parameters
                            (LayerList (list (LayerList (list (Linear 1 1)))
                                             (LayerList (list (Linear 1 1)))))))
                  '("0.0.weight" "0.0.bias" "1.0.weight" "1.0.bias"))
    (check-equal? (named-children (Dropout)) '())
    (check-equal? (children (Dropout)) '())
    (check-true (layer-list? (LayerList '())))
    (check-exn #rx"^LayerHash: contract violation"
               (lambda () (LayerHash (list (cons "a.b" (Linear 1 1)))))))

  (test-case "a layer reached by two paths contributes its parameters once"
    (manual-seed! 0)
    (define shared (Linear 2 2))
    (define-layer Tied (a b both)
      #:init ()
      (set! a shared)
      (set! b shared)
      (set! both (LayerList (list shared shared)))
      #:forward (x) (b (a x)))
    (define t (Tied))
    (check-equal? (map car (named-parameters t)) '("a.weight" "a.bias"))
    (check-equal? (parameters t) (parameters shared))
    (check-equal? (map car (named-children t)) '("a" "both"))
    (check-equal? (map car (state-dict t))
                  '("a.weight" "a.bias" "b.weight" "b.bias"
                    "both.0.weight" "both.0.bias" "both.1.weight" "both.1.bias"))
    (check-equal? (map car (named-children (cadr (children t)))) '("0"))
    (check-equal? (map car (named-parameters (cadr (children t))))
                  '("0.weight" "0.bias")))

  (test-case "own parameters come before children's, each in declaration order"
    (define-layer Interleaved (fc1 w fc2 v)
      #:init ()
      (set! fc1 (Linear 1 1))
      (set! w (Parameter (ones 1)))
      (set! fc2 (Linear 1 1))
      (set! v (Parameter (ones 1)))
      #:forward (x) x)
    (check-equal? (map car (named-parameters (Interleaved)))
                  '("w" "v" "fc1.weight" "fc1.bias" "fc2.weight" "fc2.bias")))

  (test-case "a bare tensor is a plain field; only Parameter and Buffer register"
    (define-layer Plain (t)
      #:init ()
      (set! t (ones 3))
      #:forward (x) (add x t))
    (define p (Plain))
    (check-equal? (parameters p) '())
    (check-equal? (buffers p) '())
    (check-equal? (tensor->list (p (zeros 3))) '(1.0 1.0 1.0)))

  (test-case "a field that names an #:init argument starts as that argument"
    (define-layer Scaled (scale w)
      #:init (scale #:width [width 2])
      (set! scale (* 2 scale))
      (set! w (Parameter (ones width)))
      #:forward (x) (mul x scale))
    (define s (Scaled 3))
    (check-equal? (tensor->list (s (ones 1))) '(6.0))
    (check-equal? (map tensor-shape (parameters s)) '((2))))

  (test-case "without #:init the fields are the constructor formals"
    (define-layer Pool (kernel #:stride [stride #f] #:pad [pad 0])
      #:forward (x) (list kernel stride pad))
    (check-equal? ((Pool 2) 'x) '(2 #f 0))
    (check-equal? ((Pool 3 #:stride 1 #:pad 1) 'x) '(3 1 1))
    (check-equal? (parameters (Pool 2)) '()))

  (test-case "#:init takes a rest argument, as #:rest or dotted"
    (define-layer Stack (layers)
      #:init (#:rest ms)
      (set! layers (LayerList ms))
      #:forward (x)
      (for/fold ([acc x]) ([m (in-layers layers)]) (m acc)))
    (define-layer Stack2 (layers)
      #:init (first . rest)
      (set! layers (children-by-key (list (cons "s" (LayerList (cons first rest))))))
      #:forward (x) x)
    (manual-seed! 0)
    (define st (Stack (Linear 2 3) (Linear 3 1)))
    (check-equal? (map car (named-parameters st))
                  '("layers.0.weight" "layers.0.bias"
                    "layers.1.weight" "layers.1.bias"))
    (check-equal? (tensor-shape (st (randn 4 2))) '(4 1))
    (check-equal? (map car (named-parameters (Stack2 (Linear 1 1) (Linear 1 1))))
                  '("s.0.weight" "s.0.bias" "s.1.weight" "s.1.bias")))

  (test-case "spliced children are named by index alone, as Sequential's are"
    (define-layer Seq (layers)
      #:init (#:rest ms)
      (set! layers (children-by-index ms))
      #:forward (x) x)
    (define s (Seq (Linear 1 1) (Dropout) (Linear 1 1)))
    (check-equal? (map car (named-parameters s))
                  '("0.weight" "0.bias" "2.weight" "2.bias"))
    (check-equal? (map car (named-children s)) '("0" "1" "2"))
    (check-equal? (map car (named-children (Sequential (Linear 1 1) (Dropout))))
                  '("0" "1"))
    (define ll (LayerList (list (Linear 1 1) (Dropout) (Linear 1 1))))
    (check-true (layer-list? ll))
    (check-equal? (map car (named-children ll)) '("0" "1" "2"))
    (check-equal? (for/list ([m (in-layers ll)]) m) (children ll))
    (check-equal? (for/list ([m (in-layers (LayerList '()))]) m) '())
    (check-equal? (for/list ([m (in-layers (children-by-index (list relu)))])
                    (object-name m))
                  '(Fn))
    (check-exn #rx"^in-layers: contract violation" (lambda () (in-layers 5)))
    (check-exn #rx"LayerList: not applicable" (lambda () (ll (ones 1)))))

  (test-case "a layer listed twice is applied twice but counted once"
    (define twice (procedure->Layer (lambda (x) (mul x 2))))
    (define ll (LayerList (list twice twice)))
    (check-equal? (length (for/list ([m (in-layers ll)]) m)) 2)
    (check-equal? (length (children ll)) 1)
    (check-equal? (tensor->list ((Sequential (list twice twice)) (ones 1)))
                  '(4.0))
    (define block (Linear 1 1))
    (define tied (Sequential block block))
    (check-equal? (map car (named-parameters tied)) '("0.weight" "0.bias"))
    (check-equal? (length (for/list ([m (in-layers tied)]) m)) 2)
    (check-equal? (tensor->list (tied (ones 1)))
                  (tensor->list (block (block (ones 1))))))

  (test-case "LayerHash names its children by key; child-ref looks one up"
    (manual-seed! 0)
    (define h (LayerHash (list (cons "enc" (Linear 2 3))
                               (cons "dec" (Linear 3 2))
                               (cons "act" relu))))
    (check-true (layer-hash? h))
    (check-equal? (map car (named-parameters h))
                  '("enc.weight" "enc.bias" "dec.weight" "dec.bias"))
    (check-equal? (map car (named-children h)) '("enc" "dec" "act"))
    (check-true (linear? (child-ref h "dec")))
    (check-equal? (tensor-shape ((child-ref h "dec") (ones 1 3))) '(1 2))
    (check-false (child-ref h "missing"))
    (check-equal? (for/list ([m (in-layers h)]) m) (children h))
    (check-exn #rx"^LayerHash: two children would share a name"
               (lambda () (LayerHash (list (cons "a" (Linear 1 1))
                                           (cons "a" (Linear 1 1))))))
    (check-exn #rx"LayerHash: not applicable" (lambda () (h (ones 1))))
    (define-layer Owner (parts)
      #:init ()
      (set! parts (LayerHash (list (cons "a" (Linear 1 1)))))
      #:forward (x) ((child-ref parts "a") x))
    (check-equal? (map car (named-parameters (Owner)))
                  '("parts.a.weight" "parts.a.bias")))

  (test-case "a plain procedure is a step of Sequential and a child of a LayerList"
    (define-layer MLP (fn)
      #:init (d-in d-hidden d-out)
      (set! fn (Sequential (Linear d-in d-hidden) relu
                           (Linear d-hidden d-out) (lambda (t) (mul t 2))))
      #:forward (x) (fn x))
    (manual-seed! 0)
    (define net (MLP 4 3 2))
    (define ll (car (children net)))
    (check-equal? (map car (named-parameters net))
                  '("fn.0.weight" "fn.0.bias" "fn.2.weight" "fn.2.bias"))
    (check-equal? (map car (named-children ll)) '("0" "1" "2" "3"))
    (check-true (andmap layer? (children ll)))
    (check-equal? (object-name (cadr (children ll))) 'Fn)
    (check-equal? (parameters (cadr (children ll))) '())
    (define x (randn 5 4))
    (define steps (children ll))
    (check-equal? (tensor->list (net x))
                  (tensor->list
                   (mul ((list-ref steps 2) (relu ((list-ref steps 0) x))) 2)))
    (check-true (layer-training? (train! (eval! net))))
    (check-exn #rx"^Sequential: contract violation"
               (lambda () (Sequential (Linear 1 1) 'relu))))

  (test-case "Sequential forwards through layer-forward, so a step need not be applicable"
    (struct Plus ()
      #:methods gen:layer
      [(define (layer-forward self . inputs) (add (car inputs) 1))])
    (check-false (procedure? (Plus)))
    (check-equal? (parameters (Plus)) '())
    (check-equal? (state-dict (Plus)) '())
    (check-equal? (children (Plus)) '())
    (check-true (layer-training? (eval! (Plus))))
    (define s (Sequential (Plus) relu (Plus)))
    (check-equal? (tensor->list (s (zeros 2))) '(2.0 2.0))
    (check-equal? (tensor->list (s (full -5.0 2))) '(1.0 1.0)))

  (test-case "Sequential takes its steps as arguments or as one list"
    (manual-seed! 0)
    (define spread (Sequential (Linear 2 2) relu (Linear 2 4)))
    (manual-seed! 0)
    (define listed (Sequential (list (Linear 2 2) relu (Linear 2 4))))
    (check-equal? (map car (named-parameters listed))
                  '("0.weight" "0.bias" "2.weight" "2.bias"))
    (check-equal? (map car (named-parameters spread))
                  (map car (named-parameters listed)))
    (define x (randn 3 2))
    (check-equal? (tensor->list (spread x)) (tensor->list (listed x)))
    (check-equal? (tensor->list ((Sequential) x)) (tensor->list x))
    (check-equal? (tensor->list ((Sequential '()) x)) (tensor->list x))
    (check-exn #rx"^Sequential: contract violation"
               (lambda () (Sequential (list (Linear 1 1)) (Linear 1 1))))
    (check-exn #rx"^Sequential: contract violation"
               (lambda () (Sequential (list (Linear 1 1) 'relu)))))

  (test-case "LayerList nests under a field and forwards training mode"
    (define-layer Outer (blocks)
      #:init ()
      (set! blocks (Sequential (Linear 1 1) (Dropout #:p 0.5)))
      #:forward (x) (blocks x))
    (define o (Outer))
    (check-equal? (map car (named-parameters o)) '("blocks.0.weight" "blocks.0.bias"))
    (check-true (layer-training? o))
    (eval! o)
    (check-false (layer-training? o))
    (check-false (layer-training? (cadr (children (car (children o))))))
    (train! o)
    (check-true (layer-training? o)))

  (test-case "Parameter and Buffer are tensors that keep their identity"
    (define t (ones 2))
    (define p (Parameter t))
    (check-true (tensor? p))
    (check-true (Parameter? p))
    (check-false (Parameter? t))
    (check-false (Buffer? p))
    (check-true (requires-grad? p))
    (check-equal? (tensor->list (add p p)) '(2.0 2.0))
    (define derived (Parameter (mul (requires-grad! (ones 2)) 2)))
    (backward! (sum (mul derived derived)))
    (check-true (has-grad? derived))
    (check-equal? (tensor->list (grad derived)) '(4.0 4.0))
    (define b (Buffer (zeros 2)))
    (check-true (tensor? b))
    (check-true (Buffer? b))
    (check-false (Parameter? b))
    (check-false (requires-grad? b))
    (define cut (Buffer (mul (requires-grad! (ones 2)) 2)))
    (check-false (requires-grad? cut) "a buffer is detached from the graph")
    (check-equal? (tensor->list cut) '(2.0 2.0))
    (check-exn #rx"^Parameter: contract violation" (lambda () (Parameter 5)))
    (check-exn #rx"^Buffer: contract violation" (lambda () (Buffer 'x)))
    (check-exn #rx"^LayerList: contract violation"
               (lambda () (LayerList (list 1 2)))))

  (test-case "#:reflection-name and #:init may come in either order"
    (define-layer A (w)
      #:reflection-name 'Renamed
      #:init ()
      (set! w (Parameter (ones 1)))
      #:forward (x) x)
    (define-layer B (w)
      #:init ()
      (set! w (Parameter (ones 1)))
      #:reflection-name 'Renamed
      #:forward (x) x)
    (check-equal? (object-name (A)) 'Renamed)
    (check-equal? (object-name (B)) 'Renamed)
    (check-equal? (map car (named-parameters (B))) '("w")))

  (test-case "a field name may not contain a dot"
    (check-exn #rx"a field name may not contain a dot"
               (lambda ()
                 (convert-compile-time-error
                  (let ()
                    (define-layer Dotted (encoder.block)
                      #:init ()
                      (set! encoder.block (Linear 1 1))
                      #:forward (x) x)
                    (Dotted))))))

  (test-case "training mode is per instance: leaves flip, parents keep their own"
    (define lin (Linear 1 1))
    (check-true (layer-training? lin))
    (eval! lin)
    (check-false (layer-training? lin))
    (train! lin)
    (define-layer Gate (scale)
      #:init ()
      (set! scale (Parameter (full 2.0 1)))
      #:training training?
      #:forward (x) (if training? (mul x scale) x))
    (define g (Gate))
    (check-equal? (tensor->list (g (ones 1))) '(2.0))
    (eval! g)
    (check-equal? (tensor->list (g (ones 1))) '(1.0))
    (train! g)
    (check-equal? (tensor->list (g (ones 1))) '(2.0))
    (define parent (Sequential lin g))
    (eval! g)
    (check-true (layer-training? parent) "a child's mode is not the parent's")
    (check-false (layer-training? g))
    (in-eval-mode parent
      (check-false (layer-training? parent))
      (check-false (layer-training? lin)))
    (check-true (layer-training? parent) "restored exactly")
    (check-true (layer-training? lin))
    (check-false (layer-training? g) "the hand-set child came back in eval")
    (check-exn #rx"boom" (lambda () (in-eval-mode parent (error "boom"))))
    (check-true (layer-training? parent) "restored after an exception")
    (check-false (layer-training? g))
    (define wrapped (procedure->Layer values))
    (eval! wrapped)
    (check-false (layer-training? wrapped) "a procedure layer has its own mode")
    (check-exn #rx"unbound identifier"
               (lambda ()
                 (convert-compile-time-error
                  (let ()
                    (define-layer NoMode ()
                      #:forward (x) training?)
                    (NoMode)))))
    (check-exn #rx"define-layer"
               (lambda ()
                 (convert-compile-time-error
                  (let ()
                    (define-layer BadMode ()
                      #:training 5
                      #:forward (x) x)
                    (BadMode))))))

  (test-case "with #:init, a field with a default or keyword is a syntax error"
    (check-exn #rx"with #:init, a field is a bare identifier"
               (lambda ()
                 (convert-compile-time-error
                  (let ()
                    (define-layer Bad ([w #f])
                      #:init ()
                      #:forward (x) x)
                    (Bad)))))
    (check-exn #rx"with #:init, a field is a bare identifier"
               (lambda ()
                 (convert-compile-time-error
                  (let ()
                    (define-layer Bad (#:w w)
                      #:init ()
                      #:forward (x) x)
                    (Bad)))))))
