#lang racket/base

;; Run: raco test torch/tests/python-cross-test.rkt (inside `nix develop`,
;; which provides Python torch; SKIPS when python3 can't import torch).

(module+ test
  (require (only-in json string->jsexpr)
           (only-in racket/file file->bytes make-temporary-file)
           (only-in racket/list append* append-map make-list range)
           rackunit
           "../data/loader.rkt"
           "../main.rkt"
           "../nn.rkt"
           (only-in "../data/mnist.rkt" load-mnist-fixture)
           (only-in "../data/text.rkt"
                    contiguous-blocks encode load-text-fixture text->vocab)
           (only-in "../data/translation.rkt"
                    eos-id load-translation-fixture pad-id pairs->tensors
                    pairs->vocabs sos-id vocab-size)
           (only-in "../vision/cifar10.rkt" load-cifar10-fixture)
           (only-in "../vision/diffusion.rkt"
                    UNet linear-schedule q-sample schedule-steps)
           (only-in "../vision/resnet.rkt" ResNet)
           (only-in "../vision/ppm.rkt" image-grid write-ppm)
           "private/python-env.rkt")

  ;; nn.Linear plus an int64 counter, the half_dtypes.py twin's Counted
  (define-layer BrainCounted (lin steps)
    #:init ()
    (set! lin (Linear 3 2))
    (set! steps (Buffer (tensor '(0 1))))
    #:forward (x) (lin x))

  ;; one buffer per safetensors dtype tag, the safetensors_dtypes.py twin
  (define-layer Tagged (f32 f64 f16 bf16 i64 bool u8)
    #:init ()
    (set! f32 (Buffer (zeros 2 3)))
    (set! f64 (Buffer (zeros 3 #:dtype 'float64)))
    (set! f16 (Buffer (zeros 2 2 #:dtype 'float16)))
    (set! bf16 (Buffer (zeros 4 #:dtype 'bfloat16)))
    (set! i64 (Buffer (zeros 2 2 #:dtype 'int64)))
    (set! bool (Buffer (zeros 3 #:dtype 'bool)))
    (set! u8 (Buffer (zeros 3 #:dtype 'uint8)))
    #:forward (x) x)

  (define (hex->bytes s)
    (apply bytes
           (for/list ([i (in-range 0 (string-length s) 2)])
             (string->number (substring s i (+ i 2)) 16))))

  (define (check-parity rel-path compute)
    (define j (python-result rel-path))
    (define py-values (hash-ref j 'values))
    (define t (compute))
    (check-equal? (tensor-shape t) (hash-ref j 'shape)
                  (format "~a: shape parity" rel-path))
    (define rkt-values (tensor->list t))
    (check-equal? (length rkt-values) (length py-values)
                  (format "~a: value count" rel-path))
    (for ([r (in-list rkt-values)]
          [p (in-list py-values)]
          [i (in-naturals)])
      (check-= r p tol (format "~a: value ~a parity" rel-path i)))
    (check-equal? (tensor->repr t) (hash-ref j 'repr)
                  (format "~a: repr parity" rel-path)))

  (cond
    [(not (python-torch-available?))
     (printf "[python-cross-test] skipped: python3 `torch` not available ~a\n"
             "(run inside `nix develop`)")]
    [else
     (check-parity "python/00_randn.py"
                   (lambda ()
                     (manual-seed! 0)
                     (randn 2 2)))
     (check-parity "python/01_arith.py"
                   (lambda ()
                     (define x (tensor '((1.0 -2.0) (3.0 -4.0))))
                     (* (+ x 1) (relu x))))
     (check-parity "python/02_matmul.py"
                   (lambda ()
                     (define a (reshape (arange 6) 2 3))
                     (@ a (t a 0 1))))
     (check-parity "python/03_autograd.py"
                   (lambda ()
                     (define x (tensor '(1.0 2.0 3.0) #:requires-grad? #t))
                     (backward! (~> x (* x) Σ))
                     (grad x)))
     (let* ([j (python-result "python/summarized_reprs.py")]
            [py (hash-ref j 'reprs)]
            [rkt (list
                  (tensor->repr (tensor (build-list 2000 values)))
                  (tensor->repr (zeros 1024 1024))
                  (tensor->repr (zeros 3 4 500))
                  (tensor->repr (zeros 1024 2 2))
                  (tensor->repr (zeros 1001))
                  (tensor->repr (eq (tensor '(1 2)) 1))
                  (tensor->repr (eq (zeros 2000) 1.0))
                  (tensor->repr
                   (tensor (build-list 2000 (lambda (i) (* i 1000000)))))
                  (tensor->repr
                   (tensor (build-list 30 (lambda (i) (* i 1000000)))))
                  (tensor->repr (zeros 6 6 6 5))
                  (tensor->repr (zeros 2 18))
                  (tensor->repr (zeros 30))
                  (tensor->repr (full 100.0 30))
                  (tensor->repr (full +inf.0 30))
                  (tensor->repr
                   (tensor (build-list
                            2000
                            (lambda (i) (* (add1 i) 100000000)))))
                  (tensor->repr (tensor '(1e10 2.5e10 -3e-7)))
                  (tensor->repr (tensor '(1e8)))
                  (tensor->repr (tensor '(+nan.0 5.0)))
                  (tensor->repr
                   (tensor (for/list ([i (in-range 2000)])
                             (* (exact->inexact (add1 i))
                                12345.6789))))
                  (tensor->repr (zeros 7 7 7 7 7)))])
       (check-equal? (length rkt) (length py)
                     "summarized-repr form count")
       (check-equal? (tensor->list (to-dtype (tensor '(16777217 1))
                                             'float64))
                     (hash-ref j 'f64_values))
       (for ([r (in-list rkt)]
             [p (in-list py)]
             [i (in-naturals)])
         (check-equal? r p (format "summarized repr ~a parity" i))))
     (check-parity "python/int64_inference.py"
                   (lambda ()
                     (define x (tensor '((1 2) (3 4))))
                     (@ x x)))
     ;; ref spec forms, in lockstep with the twin's `forms` list
     (let* ([j (python-result "python/indexing_parity.py")]
            [py (hash-ref j 'forms)]
            [ix (tensor '((1 2 3) (4 5 6)))]
            [c (arange 6)]
            [cube (tensor '(((1 2) (3 4)) ((5 6) (7 8))))]
            [form (lambda (x)
                    (list (shape x)
                          (for/list ([v (in-list (tensor->list x))])
                            (exact->inexact v))))]
            [rkt (list (form (ref ix 0))
                       (form (ref ix (: 1 3)))
                       (form (ref c (:: 1 5 2)))
                       (form (ref c (: _ _ 2)))
                       (form (ref ix : (:~ 1)))
                       (form (ref ix .. 0))
                       (form (ref ix : _))
                       (form (ref cube 1 .. 0))
                       (form (ref ix (gt ix 4)))
                       (form (ref ix (ne (tensor '(0 1)) 0)))
                       (form (ref ix '(-1 0)))
                       (form (ref cube (ne (tensor '((1 0) (0 1))) 0)))
                       (form (ref ix '(0 0 1)))
                       (form (ref ix '(1 0) 0))
                       (form (ref c (to-dtype (tensor '(4 0)) 'int64)))
                       (exact->inexact (ref ix 1 2))
                       (form (car (where (gt ix 4))))
                       (form (cadr (where (gt ix 4))))
                       (form (gather ix 1 (to-dtype (tensor '((0 2) (1 0)))
                                                    'int64)))
                       (form (take ix '(0 5 3)))
                       (form (take-along-dim
                              ix
                              (to-dtype (tensor '(5 0 2)) 'int64)))
                       (form (take ix '(-1 0 -6)))
                       (form (car (where (gt (tensor 1) 0))))
                       (form (car (where (gt (tensor 0) 0))))
                       (form (where (gt ix 2) ix (zeros 2 3)))
                       (form (where (gt ix 2) ix -1))
                       (form (where (gt ix 2) -5 ix))
                       (form (where (gt ix 2) ix -1.5))
                       (form (where (gt ix 2) -5.5 ix))
                       (form (where (gt ix 2) 1 0))
                       (form (where (gt ix 2) 1.5 0.5)))])
       (check-equal? (length rkt) (length py) "indexing form count")
       (for ([r (in-list rkt)]
             [p (in-list py)]
             [i (in-naturals)])
         (check-equal? r p (format "indexing form ~a parity" i))))
     ;; ref! / write-op forms, in lockstep with the twin's `forms` list
     (let* ([j (python-result "python/writes_parity.py")]
            [py (hash-ref j 'forms)]
            [fresh (lambda () (tensor '((1.0 2.0 3.0) (4.0 5.0 6.0))))]
            [i64 (lambda (v) (to-dtype (tensor v) 'int64))]
            [form (lambda (x)
                    (list (shape x)
                          (for/list ([v (in-list (tensor->list x))])
                            (exact->inexact v))))]
            [written (lambda (mutate!)
                       (define t (fresh))
                       (mutate! t)
                       (form t))]
            [rkt (list
                  (written (lambda (t) (ref! t 0 9)))
                  (written (lambda (t) (ref! t 1 2 0)))
                  (written (lambda (t) (ref! t -1 -1 0)))
                  (written (lambda (t) (ref! t (: 1 3) 7)))
                  (written (lambda (t) (ref! t : (: _ _ 2) 0)))
                  (written (lambda (t) (ref! t .. 0 5)))
                  (written (lambda (t) (ref! t : 1 (tensor '(8.0 9.0)))))
                  (written (lambda (t) (ref! t 0 (tensor '(7.0 8.0 9.0)))))
                  (let ([z (tensor 5.0)])
                    (ref! z .. 7)
                    (form (reshape z 1)))
                  (written (lambda (t) (ref! t (gt t 4.0) -1)))
                  (written (lambda (t) (ref! t (gt t 4.0) (tensor 0.0))))
                  (written (lambda (t)
                             (ref! t (gt t 3.0) (tensor '(7.0 8.0 9.0)))))
                  (written (lambda (t) (ref! t (ne (tensor '(1 0)) 0) 0)))
                  (written (lambda (t)
                             (ref! t (ne (tensor '(0 1)) 0)
                                   (tensor '(7.0 8.0 9.0)))))
                  (written (lambda (t)
                             (ref! t (ne (tensor '(1 0)) 0) (tensor '(7.0)))))
                  (written (lambda (t)
                             (ref! t (ne (tensor '(1 1)) 0)
                                   (tensor '((7.0) (8.0))))))
                  (written (lambda (t) (index-fill! t 0 (i64 '(1)) 3.5)))
                  (written (lambda (t)
                             (index-copy! t 0 (i64 '(0))
                                          (tensor '((9.0 9.0 9.0))))))
                  (written (lambda (t)
                             (index-add! t 0 (i64 '(0))
                                         (tensor '((1.0 1.0 1.0)))
                                         #:alpha 2)))
                  (written (lambda (t) (scatter! t 1 (i64 '((0) (2))) 5)))
                  (written (lambda (t)
                             (scatter! t 1 (i64 '((0) (2)))
                                       (tensor '((70.0) (80.0))))))
                  (written (lambda (t)
                             (scatter-add! t 1 (i64 '((0) (0)))
                                           (tensor '((1.0) (1.0))))))
                  (written (lambda (t) (masked-fill! t (gt t 5.0) 0)))
                  (written (lambda (t)
                             (masked-scatter! t (gt t 4.0)
                                              (tensor '(9.0 10.0)))))
                  (written (lambda (t)
                             (ref! t (gt t 4.0) (tensor '((9.0 10.0))))))
                  (written (lambda (t)
                             (ref! t (gt t 4.0) (tensor '(((7.0)))))))
                  (written (lambda (t)
                             (ref! t : 0 (tensor '((8.0 9.0))))))
                  (written (lambda (t)
                             (ref! t 0 (tensor '(((7.0 8.0 9.0))))))))])
       (check-equal? (length rkt) (length py) "write form count")
       (for ([r (in-list rkt)]
             [p (in-list py)]
             [i (in-naturals)])
         (check-equal? r p (format "write form ~a parity" i))))
     (let ()
       (define-layer mlp (fc1 fc2)
         #:init (d-in d-hidden d-out)
         (set! fc1 (Linear d-in d-hidden))
         (set! fc2 (Linear d-hidden d-out))
         #:forward (x)
         (fc2 (relu (fc1 x))))
       (define j (python-result "python/04_mlp.py"))
       (manual-seed! 0)
       (define net (mlp 4 8 2))
       (define x (randn 16 4))
       (define y (randn 16 2))
       (define opt (sgd (parameters net) #:lr 0.1))
       (define losses
         (for/list ([_ (in-range 5)])
           (zero-grads! opt)
           (define loss (mse-loss (net x) y))
           (backward! loss)
           (step! opt)
           (item loss)))
       (for ([r (in-list losses)]
             [p (in-list (hash-ref j 'losses))]
             [i (in-naturals)])
         (check-= r p tol (format "04_mlp: loss at step ~a" i)))
       (define flat-params
         (cat (for/list ([p (in-list (parameters net))])
                (reshape p -1))))
       (check-equal? (tensor-shape flat-params) (hash-ref j 'shape)
                     "04_mlp: parameter count")
       (for ([r (in-list (tensor->list flat-params))]
             [p (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= r p tol (format "04_mlp: parameter ~a parity" i))))
     (let ()
       ;; Re-declared (torch/ can't reach examples/ once installed by copy in
       ;; the nix build): MUST stay in sync with examples/racket/05-mnist.rkt
       ;; — model, seed, steps, lr, full-batch regime. The shape guard below
       ;; catches structural drift; a forward/recipe edit surfaces as a
       ;; loss-parity mismatch. Same contract for the 06 gpt twin below.
       (define-layer convnet (c1 c2 f1 f2)
         #:init ()
         (set! c1 (Conv2d 1 16 3))
         (set! c2 (Conv2d 16 32 3))
         (set! f1 (Linear 800 128))
         (set! f2 (Linear 128 10))
         #:forward (x)
         (~> x
             c1 relu (max-pool2d 2)
             c2 relu (max-pool2d 2)
             (flatten 1) f1 relu
             f2))
       (check-equal? (map tensor-shape (parameters (convnet)))
                     '((16 1 3 3) (16) (32 16 3 3) (32)
                       (128 800) (128) (10 128) (10))
                     "convnet shape must match examples/racket/05-mnist.rkt")
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs ys) (load-mnist-fixture))
           (define net (convnet))
           (define opt (adam (parameters net) #:lr 0.001))
           (define losses
             (for/list ([_ (in-range 5)])
               (zero-grads! opt)
               (define loss (cross-entropy (net xs) ys))
               (backward! loss)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       (check-training-twin "05_mnist" "python/05_mnist.py" train-on 'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "05_mnist" "python/05_mnist.py" train-on
                              'cuda 5e-3))
       ;; the same convnet on shuffled minibatches: the loader replays
       ;; DataLoader(generator=g)'s batch order, so the losses match
       (define js (python-check "mnist_shuffle.py"))
       (with-default-device 'cpu
         (manual-seed! 0)
         (define-values (sxs sys) (load-mnist-fixture))
         (define snet (convnet))
         (define sopt (adam (parameters snet) #:lr 0.001))
         (define sloader
           (dataloader (tensor-dataset sxs sys) #:batch-size 64 #:shuffle? #t
                       #:generator (make-generator 0)))
         (define slosses
           (for/list ([(_epoch xb yb) (in-epochs sloader 2)])
             (zero-grads! sopt)
             (define loss (cross-entropy (snet xb) yb))
             (backward! loss)
             (step! sopt)
             (item loss)))
         (check-equal? (length slosses) (length (hash-ref js 'losses)))
         (for ([r (in-list slosses)] [p (in-list (hash-ref js 'losses))]
               [i (in-naturals)])
           (check-= r p tol (format "mnist shuffle twin: loss ~a" i)))
         (for ([r (in-list (append-map tensor->list (parameters snet)))]
               [p (in-list (hash-ref js 'params))]
               [i (in-naturals)])
           (check-= r p tol (format "mnist shuffle twin: parameter ~a" i)))))
     (let ()
       (define-layer causal-self-attention (n-embd n-head wq wk wv wo)
         #:init (n-embd n-head)
         (unless (zero? (remainder n-embd n-head))
           (error 'causal-self-attention
                  "n-embd ~a not divisible by n-head ~a" n-embd n-head))
         (set! wq (Linear n-embd n-embd))
         (set! wk (Linear n-embd n-embd))
         (set! wv (Linear n-embd n-embd))
         (set! wo (Linear n-embd n-embd))
         #:forward (x)
         (with-default-device (tensor-device x)
           (define shape (tensor-shape x))
           (define batch (car shape))
           (define seq-len (cadr shape))
           (define head-dim (quotient n-embd n-head))
           (define (split-heads m)
             (transpose (reshape m batch seq-len n-head head-dim) 1 2))
           (define q (split-heads (wq x)))
           (define k (split-heads (wk x)))
           (define v (split-heads (wv x)))
           (define scores (/ (matmul q (transpose k 2 3)) (sqrt head-dim)))
           (define causal (eq (tril (ones seq-len seq-len)) 0))
           (define att (softmax (masked-fill scores causal -inf.0) -1))
           (~> (matmul att v) (transpose 1 2) (reshape batch seq-len n-embd) wo)))
       (define-layer feed-forward (fc1 fc2)
         #:init (n-embd)
         (set! fc1 (Linear n-embd (* 4 n-embd)))
         (set! fc2 (Linear (* 4 n-embd) n-embd))
         #:forward (x)
         (~> x fc1 gelu fc2))
       (define-layer pre-norm-residual (norm branch)
         #:init (n-embd branch)
         (set! norm (LayerNorm n-embd))
         #:forward (x)
         (~> x norm branch (+ x)))
       (define-layer gpt-block (attention mlp)
         #:init (n-embd n-head)
         (set! attention
               (pre-norm-residual n-embd (causal-self-attention n-embd n-head)))
         (set! mlp (pre-norm-residual n-embd (feed-forward n-embd)))
         #:forward (x)
         (~> x attention mlp))
       (define-layer gpt (tok-emb pos-emb blocks ln-f head)
         #:init (vocab-size block-size)
         (set! tok-emb (Embedding vocab-size 32))
         (set! pos-emb (Embedding block-size 32))
         (set! blocks (Sequential (gpt-block 32 4) (gpt-block 32 4)))
         (set! ln-f (LayerNorm 32))
         (set! head (Linear 32 vocab-size))
         #:forward (idx)
         (with-default-device (tensor-device idx)
           (define seq-len (cadr (tensor-shape idx)))
           (define pos (to-dtype (arange seq-len) 'int64))
           (~> (add (tok-emb idx) (pos-emb pos))
               blocks ln-f head)))
       (define text (load-text-fixture))
       (define vocab (text->vocab text))
       (define v-size (vector-length vocab))
       (define block-shapes
         '((32) (32)
           (32 32) (32) (32 32) (32)
           (32 32) (32) (32 32) (32)
           (32) (32)
           (128 32) (128) (32 128) (32)))
       (check-equal? (map tensor-shape (parameters (gpt v-size 16)))
                     (append (list (list v-size 32) '(16 32))
                             block-shapes block-shapes
                             (list '(32) '(32) (list v-size 32)
                                   (list v-size)))
                     "gpt shape must match examples/racket/06-gpt.rkt")
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs ys) (contiguous-blocks (encode vocab text) 16))
           (define net (gpt v-size 16))
           (define opt (adam (parameters net) #:lr 0.001))
           (define losses
             (for/list ([_ (in-range 5)])
               (zero-grads! opt)
               (define loss (cross-entropy (reshape (net xs) -1 v-size)
                                           (reshape ys -1)))
               (backward! loss)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       (check-training-twin "06_gpt" "python/06_gpt.py" train-on 'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "06_gpt" "python/06_gpt.py" train-on
                              'cuda 5e-3)))
     (let ()
       ;; Re-declared like the gpt above: MUST stay in sync with
       ;; examples/racket/12-char-rnn.rkt
       (define-layer char-rnn (embed lstm head)
         #:init (vocab-size)
         (set! embed (Embedding vocab-size 32))
         (set! lstm (LSTM 32 64 #:batch-first? #t))
         (set! head (Linear 64 vocab-size))
         #:forward (idx)
         (define-values (out _h _c) (lstm (embed idx)))
         (head out))
       (define text (load-text-fixture))
       (define vocab (text->vocab text))
       (define v-size (vector-length vocab))
       (check-equal? (map tensor-shape (parameters (char-rnn v-size)))
                     (list (list v-size 32)
                           '(256 32) '(256 64) '(256) '(256)
                           (list v-size 64) (list v-size))
                     "char-rnn shape must match examples/racket/12-char-rnn.rkt")
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs ys) (contiguous-blocks (encode vocab text) 16))
           (define net (char-rnn v-size))
           (define opt (adam (parameters net) #:lr 0.001))
           (define losses
             (for/list ([_ (in-range 5)])
               (zero-grads! opt)
               (define loss
                 (nll-loss (log-softmax (reshape (net xs) -1 v-size) 1)
                           (reshape ys -1)))
               (backward! loss)
               (clip-grad-norm! (parameters net) 1.0)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (map (lambda (p) (reshape p -1))
                             (parameters net))))))
       (check-training-twin "12_char_rnn" "python/12_char_rnn.py" train-on
                            'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "12_char_rnn" "python/12_char_rnn.py" train-on
                              'cuda 5e-3)))
     (let ()
       ;; Re-declared: MUST stay in sync with examples/racket/13-translation.rkt
       (define hidden 32)
       (define-layer encoder (embed gru)
         #:init (vocab-size)
         (set! embed (Embedding vocab-size hidden))
         (set! gru (GRU hidden hidden #:batch-first? #t))
         #:forward (tokens)
         (define-values (outputs _final) (gru (embed tokens)))
         (define at-eos
           (unsqueeze (to-dtype (eq tokens eos-id) (tensor-dtype outputs)) 1))
         (values outputs (transpose (matmul at-eos outputs) 0 1)))
       (define-layer attention (wa ua va)
         #:init ()
         (set! wa (Linear hidden hidden))
         (set! ua (Linear hidden hidden))
         (set! va (Linear hidden 1))
         #:forward (query keys padding)
         (define scores (transpose (va (tanh (+ (wa query) (ua keys)))) 1 2))
         (matmul (softmax (masked-fill scores padding -inf.0) -1) keys))
       (define-layer decoder (embed attend gru head)
         #:init (vocab-size)
         (set! embed (Embedding vocab-size hidden))
         (set! attend (attention))
         (set! gru (GRU (* 2 hidden) hidden #:batch-first? #t))
         (set! head (Linear hidden vocab-size))
         #:forward (previous state keys padding)
         (define context (attend (transpose state 0 1) keys padding))
         (define-values (output next-state)
           (gru (cat (list (embed previous) context) 2) state))
         (values (head output) next-state))
       (define-layer seq2seq (enc dec)
         #:init (source-size target-size)
         (set! enc (encoder source-size))
         (set! dec (decoder target-size))
         #:forward (sources targets teacher-forcing?)
         (define-values (keys encoded) (enc sources))
         (define padding (unsqueeze (eq sources pad-id) 1))
         (define batch (car (tensor-shape sources)))
         (define-values (logits _previous _state)
           (for/fold ([logits '()]
                      [previous (full-like (narrow sources 1 0 1) sos-id)]
                      [state encoded])
                     ([step (in-range 10)])
             (define-values (step-logits next-state)
               (dec previous state keys padding))
             (define next
               (if teacher-forcing?
                   (narrow targets 1 step 1)
                   (let-values ([(_top best) (topk step-logits 1)])
                     (detach (reshape best batch 1)))))
             (values (cons step-logits logits) next next-state)))
         (cat (reverse logits) 1))
       (define pairs (load-translation-fixture))
       (define-values (source-vocab target-vocab) (pairs->vocabs pairs))
       (define s-size (vocab-size source-vocab))
       (define v-size (vocab-size target-vocab))
       (check-equal? (map tensor-shape (parameters (seq2seq s-size v-size)))
                     (list (list s-size hidden)
                           '(96 32) '(96 32) '(96) '(96)
                           (list v-size hidden)
                           '(32 32) '(32) '(32 32) '(32) '(1 32) '(1)
                           '(96 64) '(96 32) '(96) '(96)
                           (list v-size hidden) (list v-size))
                     "seq2seq shape must match examples/racket/13-translation.rkt at #:hidden 32")
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (sources targets)
             (pairs->tensors pairs source-vocab target-vocab #:width 10))
           (define net (seq2seq s-size v-size))
           (define opt (adam (parameters net) #:lr 0.001))
           (define losses
             (for/list ([_ (in-range 5)])
               (define teacher-forcing?
                 (< (item (rand 1 #:device 'cpu)) 0.5))
               (zero-grads! opt)
               (define loss
                 (nll-loss (log-softmax
                            (reshape (net sources targets teacher-forcing?)
                                     -1 v-size)
                            1)
                           (reshape targets -1)
                           #:ignore-index pad-id))
               (backward! loss)
               (clip-grad-norm! (parameters net) 1.0)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       (check-training-twin "13_translation" "python/13_translation.py"
                            train-on 'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "13_translation" "python/13_translation.py"
                              train-on 'cuda 5e-3)))
     (let ()
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs _ys) (load-cifar10-fixture))
           (define net (UNet #:base 64 #:mults '(1 2) #:blocks 1 #:attention '(16)
                             #:dropout 0))
           (define sched (linear-schedule))
           (define opt (adam (parameters net) #:lr 0.001))
           (manual-seed! 0)
           (define n (length xs))
           (define steps (schedule-steps sched))
           (define losses
             (for/list ([_ (in-range 5)])
               (define t (to (to-dtype (mul (rand n #:device 'cpu) steps) 'int64)
                             device))
               (define noise (to (randn-like xs #:device 'cpu) device))
               (zero-grads! opt)
               (define loss (mse-loss (net (q-sample sched xs t noise) t #f) noise))
               (backward! loss)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       (check-training-twin "08_diffusion" "python/08_diffusion.py" train-on
                            'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "08_diffusion" "python/08_diffusion.py" train-on
                              'cuda 5e-3)))
     (let ()
       ;; MUST stay in sync with examples/racket/09-resnet.rkt's run-example
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs ys) (load-cifar10-fixture))
           (define net (ResNet #:base 16))
           (define opt (sgd (parameters net) #:lr 0.005 #:momentum 0.9
                            #:weight-decay 5e-4))
           (define losses
             (for/list ([_ (in-range 3)])
               (zero-grads! opt)
               (define loss (cross-entropy (net xs) ys))
               (backward! loss)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       ;; batch norm divides by the batch's own statistics, which amplifies
       ;; the last-bit kernel differences between the two torch builds; a
       ;; few of the 700k parameters land just past tol after three steps
       (check-training-twin "09_resnet" "python/09_resnet.py" train-on
                            'cpu 5e-4)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "09_resnet" "python/09_resnet.py" train-on
                              'cuda 5e-3)))
     (let ()
       ;; MUST stay in sync with examples/racket/10-dcgan.rkt: the losses
       ;; are the discriminator's and the generator's per step, interleaved,
       ;; and the parameters are the generator's then the discriminator's
       (define-layer gen-twin (fc bn0 up1 bn1 up2)
         #:init ()
         (set! fc (Linear 100 (* 128 7 7)))
         (set! bn0 (BatchNorm1d (* 128 7 7)))
         (set! up1 (ConvTranspose2d 128 64 4 #:stride 2 #:padding 1))
         (set! bn1 (BatchNorm2d 64))
         (set! up2 (ConvTranspose2d 64 1 4 #:stride 2 #:padding 1))
         #:forward (z)
         (~> z fc bn0 relu (reshape (length z) 128 7 7) up1 bn1 relu up2 tanh))
       (define-layer disc-twin (conv1 conv2 bn fc)
         #:init ()
         (set! conv1 (Conv2d 1 64 4 #:stride 2 #:padding 1))
         (set! conv2 (Conv2d 64 128 4 #:stride 2 #:padding 1))
         (set! bn (BatchNorm2d 128))
         (set! fc (Linear (* 128 7 7) 1))
         #:forward (x)
         (~> x conv1 (leaky-relu #:negative-slope 0.2)
             conv2 bn (leaky-relu #:negative-slope 0.2)
             (flatten 1) fc))
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs _ys) (load-mnist-fixture))
           (define gen (gen-twin))
           (define disc (disc-twin))
           (define opt-g (adam (parameters gen) #:lr 2e-4 #:beta1 0.5))
           (define opt-d (adam (parameters disc) #:lr 2e-4 #:beta1 0.5))
           (manual-seed! 0)
           (define n (length xs))
           (define real (sub (mul xs 2.0) 1.0))
           (define ones-target (ones n 1))
           (define zeros-target (zeros n 1))
           (define losses
             (append*
              (for/list ([_ (in-range 3)])
                (define z (to (randn n 100 #:device 'cpu) device))
                (define fake (gen z))
                (zero-grads! opt-d)
                (define d-loss
                  (add (binary-cross-entropy-with-logits (disc real) ones-target)
                       (binary-cross-entropy-with-logits (disc (detach fake))
                                                         zeros-target)))
                (backward! d-loss)
                (step! opt-d)
                (zero-grads! opt-g)
                (define g-loss
                  (binary-cross-entropy-with-logits (disc fake) ones-target))
                (backward! g-loss)
                (step! opt-g)
                (list (item d-loss) (item g-loss)))))
           (values losses
                   (cat (for/list ([p (in-list (append (parameters gen)
                                                       (parameters disc)))])
                          (reshape p -1))))))
       ;; batch norm in both networks: a few dozen of the 1.3M parameters
       ;; land just past tol after three alternating steps, as for 09_resnet
       (check-training-twin "10_dcgan" "python/10_dcgan.py" train-on 'cpu 5e-4)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "10_dcgan" "python/10_dcgan.py" train-on
                              'cuda 5e-3)))
     (let ()
       ;; MUST stay in sync with examples/racket/11-vae.rkt
       (define-layer vae-twin (enc mu-head logvar-head dec1 dec2)
         #:init ()
         (set! enc (Linear 784 400))
         (set! mu-head (Linear 400 20))
         (set! logvar-head (Linear 400 20))
         (set! dec1 (Linear 20 400))
         (set! dec2 (Linear 400 784))
         #:forward (x eps)
         (define h (relu (enc (flatten x 1))))
         (define mu (mu-head h))
         (define logvar (logvar-head h))
         (define z (add mu (mul eps (exp (mul logvar 0.5)))))
         (values (dec2 (relu (dec1 z))) mu logvar))
       (define (train-on device)
         (with-default-device device
           (manual-seed! 0)
           (define-values (xs _ys) (load-mnist-fixture))
           (define net (vae-twin))
           (define opt (adam (parameters net) #:lr 1e-3))
           (manual-seed! 0)
           (define n (length xs))
           (define losses
             (for/list ([_ (in-range 5)])
               (define eps (to (randn n 20 #:device 'cpu) device))
               (zero-grads! opt)
               (define-values (logits means logvars) (net xs eps))
               (define recon
                 (mul (binary-cross-entropy-with-logits logits (flatten xs 1))
                      784.0))
               (define kl
                 (mul (sum (sub (sub (add 1.0 logvars) (mul means means))
                                (exp logvars)))
                      (/ -0.5 n)))
               (define loss (add recon kl))
               (backward! loss)
               (step! opt)
               (item loss)))
           (values losses
                   (cat (for/list ([p (in-list (parameters net))])
                          (reshape p -1))))))
       (check-training-twin "11_vae" "python/11_vae.py" train-on 'cpu tol)
       (when (and (cuda-available?)
                  (python-cuda-available?))
         (check-training-twin "11_vae" "python/11_vae.py" train-on
                              'cuda 5e-3)))
     (let ()
       (define j (python-check "conv2d_init.py"))
       (manual-seed! 0)
       (define net (Conv2d 1 8 3))
       (define ps (parameters net))
       (check-equal? (map tensor-shape ps) (hash-ref j 'shapes)
                     "conv2d init: parameter shapes match nn.Conv2d")
       (define rkt-vals (apply append (map tensor->list ps)))
       (define py-vals (hash-ref j 'values))
       (check-equal? (length rkt-vals) (length py-vals)
                     "conv2d init: value count")
       (for ([r (in-list rkt-vals)] [p (in-list py-vals)] [i (in-naturals)])
         (check-= r p tol (format "conv2d init: value ~a parity" i))))
     (let ()
       (define j (python-check "embedding_init.py"))
       (manual-seed! 0)
       (define net (Embedding 7 4))
       (define w (car (parameters net)))
       (check-equal? (tensor-shape w) (hash-ref j 'shape)
                     "embedding init: weight shape matches nn.Embedding")
       (for ([r (in-list (tensor->list w))]
             [p (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= r p tol (format "embedding init: value ~a parity" i))))
     (let ()
       (define j (python-check "layer_norm_forward.py"))
       (manual-seed! 0)
       (define ln (LayerNorm 5))
       (define r (ln (randn 3 5)))
       (check-equal? (tensor-shape r) (hash-ref j 'shape)
                     "layer-norm forward: shape parity")
       (for ([a (in-list (tensor->list r))]
             [b (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "layer-norm forward: value ~a parity" i))))
     (let ()
       (define j (python-check "conv_transpose2d_init.py"))
       (manual-seed! 0)
       (define net (ConvTranspose2d 2 4 3))
       (define ps (parameters net))
       (check-equal? (map tensor-shape ps) (hash-ref j 'shapes)
                     "conv-transpose2d init: parameter shapes match nn.ConvTranspose2d")
       (define rkt-vals (apply append (map tensor->list ps)))
       (define py-vals (hash-ref j 'values))
       (check-equal? (length rkt-vals) (length py-vals)
                     "conv-transpose2d init: value count")
       (for ([r (in-list rkt-vals)] [p (in-list py-vals)] [i (in-naturals)])
         (check-= r p tol (format "conv-transpose2d init: value ~a parity" i))))
     (let ()
       (define j (python-check "group_norm_forward.py"))
       (manual-seed! 0)
       (define gn (GroupNorm 2 4))
       (define r (gn (randn 2 4 3 3)))
       (check-equal? (tensor-shape r) (hash-ref j 'shape)
                     "group-norm forward: shape parity")
       (for ([a (in-list (tensor->list r))]
             [b (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "group-norm forward: value ~a parity" i))))
     (let ()
       (define j (python-check "batch_norm_forward.py"))
       (manual-seed! 0)
       (define bn (BatchNorm2d 3))
       (define x (randn 2 3 4 4))
       (define r (bn x))
       (check-equal? (tensor-shape r) (hash-ref j 'shape)
                     "batch-norm forward: shape parity")
       (for ([a (in-list (tensor->list r))]
             [b (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "batch-norm forward: value ~a parity" i)))
       (define stats (buffers bn))
       (for ([a (in-list (tensor->list (car stats)))]
             [b (in-list (hash-ref j 'running_mean))]
             [i (in-naturals)])
         (check-= a b tol (format "batch-norm running mean ~a parity" i)))
       (for ([a (in-list (tensor->list (cadr stats)))]
             [b (in-list (hash-ref j 'running_var))]
             [i (in-naturals)])
         (check-= a b tol (format "batch-norm running var ~a parity" i)))
       (check-= (item (caddr stats)) (hash-ref j 'num_batches_tracked) 0
                "batch-norm batches tracked parity")
       (define e (in-eval-mode bn (bn x)))
       (for ([a (in-list (tensor->list e))]
             [b (in-list (hash-ref j 'eval_values))]
             [i (in-naturals)])
         (check-= a b tol (format "batch-norm eval: value ~a parity" i))))
     (let ()
       (define j (python-check "sgd_variants.py"))
       (define-layer mlp-twin (fc1 fc2)
         #:init ()
         (set! fc1 (Linear 4 8))
         (set! fc2 (Linear 8 2))
         #:forward (x)
         (fc2 (relu (fc1 x))))
       (define (run make-opt)
         (manual-seed! 0)
         (define net (mlp-twin))
         (define xs (randn 16 4))
         (define ys (randn 16 2))
         (define opt (make-opt (parameters net)))
         (define losses
           (for/list ([_ (in-range 5)])
             (zero-grads! opt)
             (define loss (mse-loss (net xs) ys))
             (backward! loss)
             (step! opt)
             (item loss)))
         (values losses
                 (tensor->list (cat (for/list ([p (in-list (parameters net))])
                                      (reshape p -1))))))
       (define (check-config name make-opt)
         (define expected (hash-ref j (string->symbol name)))
         (define-values (losses params) (run make-opt))
         (for ([r (in-list losses)] [p (in-list (hash-ref expected 'losses))]
               [i (in-naturals)])
           (check-= r p tol (format "~a: loss ~a" name i)))
         (for ([r (in-list params)] [p (in-list (hash-ref expected 'params))]
               [i (in-naturals)])
           (check-= r p tol (format "~a: parameter ~a" name i))))
       (check-config "momentum"
                     (lambda (ps) (sgd ps #:lr 0.1 #:momentum 0.9)))
       (check-config "nesterov"
                     (lambda (ps) (sgd ps #:lr 0.1 #:momentum 0.9
                                       #:nesterov? #t)))
       (check-config "weight_decay"
                     (lambda (ps) (sgd ps #:lr 0.1 #:momentum 0.9
                                       #:weight-decay 5e-4)))
       (check-config "adam_weight_decay"
                     (lambda (ps) (adam ps #:lr 0.05 #:weight-decay 1e-2)))
       (check-config "rmsprop" (lambda (ps) (rmsprop ps #:lr 0.01)))
       (check-config "rmsprop_momentum"
                     (lambda (ps) (rmsprop ps #:lr 0.01 #:momentum 0.9
                                           #:weight-decay 1e-3))))
     (let ()
       (define j (python-check "schedulers.py"))
       (define (rates make)
         (define opt (sgd (list (Parameter (zeros 1))) #:lr 0.1))
         (define s (make opt))
         (cons (learning-rate s)
               (for/list ([_ (in-range 11)])
                 (step! opt)
                 (step! s)
                 (learning-rate s))))
       (define (check-shape name make)
         (for ([r (in-list (rates make))]
               [p (in-list (hash-ref j (string->symbol name)))]
               [i (in-naturals)])
           (check-= r p 1e-9 (format "~a scheduler: rate at step ~a" name i))))
       (check-shape "step" (lambda (o) (step-lr o #:step-size 3 #:gamma 0.5)))
       (check-shape "multi_step"
                    (lambda (o) (multi-step-lr o #:milestones '(2 5 9)
                                               #:gamma 0.1)))
       (check-shape "exponential" (lambda (o) (exponential-lr o #:gamma 0.9)))
       (check-shape "cosine"
                    (lambda (o) (cosine-annealing-lr o #:t-max 10
                                                     #:eta-min 0.01)))
       (check-shape "linear"
                    (lambda (o) (linear-lr o #:start-factor 0.25
                                           #:end-factor 1.0 #:total-iters 4)))
       (check-shape "one_cycle"
                    (lambda (o) (one-cycle-lr o #:max-lr 1.0 #:total-steps 12)))
       (check-shape "lambda"
                    (lambda (o) (lambda-lr o (lambda (t) (/ 1.0 (add1 t)))))))
     (let ()
       (define j (python-check "make_grid_parity.py"))
       (manual-seed! 0)
       (define grid (image-grid (rand 5 3 4 4) #:columns 2 #:padding 1
                                #:pad-value 0.5))
       (check-equal? (tensor-shape grid) (hash-ref j 'shape)
                     "image-grid: shape parity with make_grid")
       (for ([a (in-list (tensor->list grid))]
             [b (in-list (hash-ref j 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "image-grid: value ~a parity" i)))
       (define path (make-temporary-file "rkt-grid-~a.ppm"))
       (write-ppm path grid)
       (define bs (file->bytes path))
       (delete-file path)
       ;; five images in two columns: three rows of 4 + 1, so 16 by 11
       (define header #"P6\n11 16\n255\n")
       (check-equal? (subbytes bs 0 (bytes-length header)) header
                     "write-ppm: header for make_grid's 16 by 11")
       (define pixels (bytes->list (subbytes bs (bytes-length header))))
       (check-equal? (length pixels) (length (hash-ref j 'pixels))
                     "write-ppm: one byte per channel")
       ;; the quantization rounds at a half, where a difference the value
       ;; check above tolerates moves a byte by one
       (for ([a (in-list pixels)]
             [b (in-list (hash-ref j 'pixels))]
             [i (in-naturals)])
         (check-= a b 1 (format "write-ppm: save_image's quantization ~a" i)))
       (manual-seed! 1)
       (define one (image-grid (rand 1 3 4 4) #:columns 2 #:padding 1
                               #:pad-value 0.5))
       (check-equal? (tensor-shape one) (hash-ref j 'one_shape)
                     "image-grid: make_grid returns one image unpadded")
       (for ([a (in-list (tensor->list one))]
             [b (in-list (hash-ref j 'one_values))]
             [i (in-naturals)])
         (check-= a b tol (format "image-grid: one image value ~a parity" i))))
     (let ()
       (define j (python-check "ema_update.py"))
       (manual-seed! 0)
       (define m (Linear 4 3))
       (define x (randn 8 4))
       (define avg (ema m (Linear 4 3) #:decay 0.9))
       (define opt (sgd (parameters m) #:lr 0.1))
       (for ([_ (in-range 3)])
         (zero-grads! opt)
         (define y (m x))
         (backward! (mean (* y y)))
         (step! opt)
         (ema-update! avg))
       (define (flat layer) (append-map tensor->list (parameters layer)))
       (for ([a (in-list (flat m))]
             [b (in-list (hash-ref j 'model))]
             [i (in-naturals)])
         (check-= a b tol (format "ema: model parameter ~a parity" i)))
       (for ([a (in-list (flat (ema-average avg)))]
             [b (in-list (hash-ref j 'average))]
             [i (in-naturals)])
         (check-= a b tol (format "ema: averaged parameter ~a parity" i))))
     (let ()
       (define j (python-check "pool_default_stride.py"))
       (manual-seed! 0)
       (define x (randn 1 1 4 4))
       (define mp (max-pool2d x 2))
       (define ap (avg-pool2d x 2))
       (for ([a (in-list (tensor->list mp))] [b (in-list (hash-ref j 'mp))]
             [i (in-naturals)])
         (check-= a b tol (format "max-pool2d default-stride parity ~a" i)))
       (for ([a (in-list (tensor->list ap))] [b (in-list (hash-ref j 'ap))]
             [i (in-naturals)])
         (check-= a b tol (format "avg-pool2d default-stride parity ~a" i))))
     (let ()
       (define jf (python-check "flatten.py"))
       (manual-seed! 0)
       (define x (randn 2 3 4))
       (define r (flatten x 1))
       (check-equal? (tensor-shape r) (hash-ref jf 'shape) "flatten parity: shape")
       (for ([a (in-list (tensor->list r))] [b (in-list (hash-ref jf 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "flatten parity ~a" i))))
     (let ()
       (define jg (python-check "gelu.py"))
       (manual-seed! 0)
       (define xg (randn 2 3))
       (define rg (gelu xg))
       (check-equal? (tensor-shape rg) (hash-ref jg 'shape)
                     "gelu parity: shape")
       (for ([a (in-list (tensor->list rg))]
             [b (in-list (hash-ref jg 'values))]
             [i (in-naturals)])
         (check-= a b tol (format "gelu parity ~a" i))))
     (let ()
       (define jt (python-check "transpose_all.py"))
       (manual-seed! 0)
       (define x2 (randn 3 4))
       (define x3 (randn 2 3 4))
       (for ([r (in-list (list (T x2) (T x3)))]
             [key (in-list '(rank2 rank3))])
         (define j (hash-ref jt key))
         (check-equal? (tensor-shape r) (hash-ref j 'shape)
                       (format "T parity: ~a shape" key))
         (for ([a (in-list (tensor->list r))]
               [b (in-list (hash-ref j 'values))]
               [i (in-naturals)])
           (check-= a b tol (format "T parity ~a ~a" key i)))))
     (define jm (python-check "causal_mask.py"))
     (manual-seed! 0)
     (define scores (randn 2 4 4))
     (define mask (eq (tril (ones 4 4)) 0))
     (define r (softmax (masked-fill scores mask -inf.0) -1))
     (check-equal? (tensor-shape r) (hash-ref jm 'shape)
                   "causal mask parity: shape")
     (for ([a (in-list (tensor->list r))]
           [b (in-list (hash-ref jm 'values))]
           [i (in-naturals)])
       (check-= a b tol (format "causal mask parity ~a" i)))
     (let ()
       (define j (python-check "to_conversions.py"))
       (define x (tensor '((1.5 -2.0) (0.0 3.25))))
       (check-equal? (tensor->list (to x 'float64)) (hash-ref j 'float64_values))
       (check-equal? (format "torch.~a" (tensor-dtype (to x 'float64)))
                     (hash-ref j 'float64_dtype))
       (check-equal? (tensor->repr (to x 'int64)) (hash-ref j 'int64_repr))
       (check-equal? (tensor->repr (to x 'bool)) (hash-ref j 'bool_repr))
       (check-equal? (format "torch.~a" (tensor-dtype (to x 'cpu 'float64)))
                     (hash-ref j 'both_dtype))
       (check-equal? (tensor->repr (zeros '(2 3) #:dtype 'int64))
                     (hash-ref j 'zeros_int64_repr))
       (check-equal? (tensor->repr (full 7 '(2) #:dtype 'int64))
                     (hash-ref j 'full_int64_repr))
       (check-equal? (tensor->repr (ones 3 #:dtype 'bool))
                     (hash-ref j 'ones_bool_repr))
       (let ()
         (define h (python-check "half_dtypes.py"))
         (manual-seed! 0)
         (define xh (randn 2 3))
         (check-equal? (tensor->list (to xh 'float16)) (hash-ref h 'half_values)
                       "float16 cast: values through float32")
         (check-equal? (tensor->list (to xh 'bfloat16))
                       (hash-ref h 'brain_values)
                       "bfloat16 cast: values through float32")
         (check-equal? (tensor->repr (to xh 'float16)) (hash-ref h 'half_repr))
         (check-equal? (tensor->repr (to xh 'bfloat16)) (hash-ref h 'brain_repr))
         (check-equal? (tensor->repr (zeros 0 #:dtype 'float16))
                       (hash-ref h 'empty_half_repr))
         (check-equal? (tensor->repr (zeros 2 2 #:dtype 'bfloat16))
                       (hash-ref h 'zeros_brain_repr))
         (check-equal? (tensor->list (full 0.1 3 #:dtype 'float16))
                       (hash-ref h 'full_half_values))
         (check-equal? (tensor->list (arange 0 5 #:dtype 'bfloat16))
                       (hash-ref h 'arange_brain_values))
         (check-equal? (tensor->list (tensor '(1.0 0.1 65504.0)
                                             #:dtype 'float16))
                       (hash-ref h 'tensor_half_values))
         (manual-seed! 1)
         (define counted (to (BrainCounted) 'bfloat16))
         (check-equal? (for/hasheq ([e (in-list (state-dict counted))])
                         (values (string->symbol (car e))
                                 (format "torch.~a" (tensor-dtype (cdr e)))))
                       (hash-ref h 'counted_dtypes)
                       "a layer moved to bfloat16 keeps its int64 buffer")
         (check-equal? (tensor->list (car (parameters counted)))
                       (hash-ref h 'counted_weight)))
       (let ()
         (define h (python-check "autocast_cpu.py"))
         (define half-tol 2e-2)
         (manual-seed! 0)
         (define a (randn 3 4))
         (define b (randn 4 2))
         (check-equal? (autocast-enabled? 'cpu) (hash-ref h 'before))
         (define prod
           (with-autocast #:device 'cpu
             (check-equal? (autocast-enabled? 'cpu) (hash-ref h 'inside))
             (matmul a b)))
         (check-equal? (autocast-enabled? 'cpu) (hash-ref h 'after))
         (check-equal? (format "torch.~a" (tensor-dtype prod))
                       (hash-ref h 'prod_dtype))
         (for ([r (in-list (tensor->list prod))]
               [p (in-list (hash-ref h 'prod_values))]
               [i (in-naturals)])
           (check-= r p half-tol (format "autocast matmul: value ~a" i)))
         (manual-seed! 1)
         (define lin (Linear 4 2))
         (define xa (randn 8 4))
         (define loss
           (with-autocast #:device 'cpu
             (define y (lin xa))
             (check-equal? (format "torch.~a" (tensor-dtype y))
                           (hash-ref h 'y_dtype))
             (mean (mul y y))))
         (check-= (item loss) (hash-ref h 'loss) half-tol "autocast loss")
         (backward! loss)
         (define g (grad (car (parameters lin))))
         (check-equal? (format "torch.~a" (tensor-dtype g))
                       (hash-ref h 'grad_dtype))
         (for ([r (in-list (tensor->list g))]
               [p (in-list (hash-ref h 'grad_values))]
               [i (in-naturals)])
           (check-= r p half-tol (format "autocast grad: value ~a" i))))
       (let ()
         (define h (python-check "safetensors_dtypes.py"))
         (define path (make-temporary-file "rkt-tagged-~a.safetensors"))
         (call-with-output-file path #:exists 'truncate
           (lambda (out) (write-bytes (hex->bytes (hash-ref h 'hex)) out)))
         (define m (Tagged))
         (load-state! m path)
         (for ([e (in-list (state-dict m))])
           (check-equal? (map exact->inexact (tensor->list (cdr e)))
                         (hash-ref (hash-ref h 'values)
                                   (string->symbol (car e)))
                         (format "safetensors ~a: values from Python's file"
                                 (car e))))
         (define ours (make-temporary-file "rkt-tagged-out-~a.safetensors"))
         (save-state! m ours)
         (define raw (file->bytes ours))
         (define header-len (integer-bytes->integer raw #f #f 0 8))
         (define header
           (string->jsexpr (bytes->string/utf-8 raw #f 8 (+ 8 header-len))))
         (for ([e (in-list (state-dict m))])
           (define meta (hash-ref header (string->symbol (car e))))
           (define offsets (hash-ref meta 'data_offsets))
           (check-equal? (subbytes raw
                                   (+ 8 header-len (car offsets))
                                   (+ 8 header-len (cadr offsets)))
                         (hex->bytes (hash-ref (hash-ref h 'payload_hex)
                                               (string->symbol (car e))))
                         (format "safetensors ~a: our payload is Python's"
                                 (car e))))
         (delete-file path)
         (delete-file ours))
       (check-equal? (format "torch.~a" (tensor-dtype (zeros-like (to x 'float64))))
                     (hash-ref j 'zeros_like_dtype))
       (check-equal? (eq? (to x 'cpu) x) (hash-ref j 'cpu_is_self))
       (check-equal? (eq? (to x 'float32) x) (hash-ref j 'dtype_is_self))
       (check-equal? (symbol->string (device-type (tensor-device x)))
                     (hash-ref j 'device_type))
       (check-equal? (cuda-available?) (hash-ref j 'cuda_available))
       (manual-seed! 0)
       (define lin (Linear 2 2))
       (check-equal? (eq? (to lin 'float64) lin) (hash-ref j 'linear_is_self))
       (check-equal? (for/list ([e (in-list (state-dict lin))])
                       (format "torch.~a" (tensor-dtype (cdr e))))
                     (hash-ref j 'linear_state_dtypes))
       (for ([a (in-list (append-map tensor->list (parameters lin)))]
             [b (in-list (hash-ref j 'linear_state_values))]
             [i (in-naturals)])
         (check-= a b tol (format "Linear.to(float64) parity ~a" i)))
       ;; Module.to forwards the dtype only to floating-point tensors
       (define-layer Counted (lin steps keep)
         #:init ()
         (set! lin (Linear 2 2))
         (set! steps (Buffer (tensor '(0 1))))
         (set! keep (Buffer (eq (tensor '(1 0)) 1)))
         #:forward (x) (lin x))
       (define counted (to (Counted) 'float64))
       (define py-dtypes (hash-ref j 'counted_dtypes))
       (check-equal? (length (state-dict counted)) (hash-count py-dtypes))
       (for ([e (in-list (state-dict counted))])
         (check-equal? (format "torch.~a" (tensor-dtype (cdr e)))
                       (hash-ref py-dtypes (string->symbol (car e)))
                       (format "Module.to(float64) dtype of ~a" (car e)))))
     (let ()
       ;; a shuffling loader replays DataLoader(generator=g)'s batch order
       (define j (python-check "dataloader_twin.py"))
       (define n 10)
       (define xs (/ (reshape (arange (* n 3)) n 3) n))
       (define ys (matmul xs (ones 3 1)))
       (define ds (tensor-dataset xs ys))
       (define (orders g epochs)
         (define loader
           (dataloader (tensor-dataset (arange n #:dtype 'int64))
                       #:batch-size 4 #:shuffle? #t #:generator g))
         (for/list ([_ (in-range epochs)])
           (for/list ([ib (in-dataloader loader)]) (tensor->list ib))))
       (check-equal? (orders (make-generator 7) 2) (hash-ref j 'loader_order)
                     "one generator across two DataLoader epochs")
       ;; without a generator the draws come from the global stream, and
       ;; leave it where DataLoader(shuffle=True) leaves it
       (manual-seed! 3)
       (check-equal? (orders #f 2) (hash-ref j 'global_order)
                     "two DataLoader epochs on the global stream")
       (for ([r (in-list (tensor->list (randn 3)))]
             [p (in-list (hash-ref j 'after_global))]
             [i (in-naturals)])
         (check-= r p tol (format "global stream after shuffling: ~a" i)))
       ;; every traversal draws the iterator's base seed, shuffled or not
       (define ids (tensor-dataset (arange n #:dtype 'int64)))
       (define g5 (make-generator 5))
       (for* ([_e (in-range 2)]
              [ib (in-dataloader (dataloader ids #:batch-size 4 #:generator g5))])
         (void ib))
       (check-equal? (tensor->list (randperm n #:generator g5))
                     (hash-ref j 'unshuffled_then)
                     "an unshuffled epoch draws its base seed")
       (manual-seed! 3)
       (for ([ib (in-dataloader (dataloader ids #:batch-size 4))])
         (void ib))
       (for ([r (in-list (tensor->list (randn 3)))]
             [p (in-list (hash-ref j 'after_global_plain))]
             [i (in-naturals)])
         (check-= r p tol (format "global stream after a plain epoch: ~a" i)))
       ;; the remainder draw waits until the first permutation is used up;
       ;; in-range first, so the loader's exhaustion check never runs
       (define (partial batch-size take)
         (define g (make-generator 11))
         (define loader
           (dataloader ids #:batch-size batch-size #:shuffle? #t #:generator g))
         (define n-first (if (eq? take 'all) (dataloader-length loader) 1))
         (hasheq 'first
                 (for/list ([_i (in-range n-first)] [ib (in-dataloader loader)])
                   (tensor->list ib))
                 'second
                 (for/list ([ib (in-dataloader loader)]) (tensor->list ib))
                 'then
                 (tensor->list (randperm n #:generator g))))
       (for ([case (in-list '((one_of_4 4 one) (all_of_4 4 all) (all_of_5 5 all)))])
         (check-equal? (partial (cadr case) (caddr case))
                       (hash-ref (hash-ref j 'partial_orders) (car case))
                       (format "partial traversal ~a" (car case))))
       (manual-seed! 0)
       (define model (Linear 3 1))
       (define opt (sgd (parameters model) #:lr 0.1))
       (define loader
         (dataloader ds #:batch-size 4 #:shuffle? #t
                     #:generator (make-generator 7)))
       (define losses
         (for*/list ([_ (in-range 2)] [(xb yb) (in-dataloader loader)])
           (zero-grads! opt)
           (define loss (mse-loss (model xb) yb))
           (backward! loss)
           (step! opt)
           (item loss)))
       (for ([r (in-list losses)] [p (in-list (hash-ref j 'losses))]
             [i (in-naturals)])
         (check-= r p tol (format "dataloader twin: loss ~a" i)))
       (for ([r (in-list (append-map tensor->list (parameters model)))]
             [p (in-list (hash-ref j 'params))]
             [i (in-naturals)])
         (check-= r p tol (format "dataloader twin: parameter ~a" i))))
     (let ()
       ;; the CIFAR-10 fixture parsed by both sides: labels, pixels, means
       (define j (python-check "cifar10_fixture.py"))
       (define-values (imgs lbls) (load-cifar10-fixture))
       (check-equal? (length lbls) (hash-ref j 'n))
       (check-equal? (tensor->list lbls) (hash-ref j 'labels))
       (define flat (tensor->list (reshape imgs 256 -1)))
       (define first-pixels
         (append (for/list ([i (in-range 8)]) (list-ref flat i))
                 (for/list ([i (in-range 1024 1028)]) (list-ref flat i))
                 (for/list ([i (in-range 2048 2052)]) (list-ref flat i))))
       (for ([r (in-list first-pixels)] [p (in-list (hash-ref j 'first_pixels))]
             [i (in-naturals)])
         (check-= r p tol (format "cifar10 fixture pixel ~a" i)))
       (for ([r (in-list (for/list ([i (in-range 256)])
                           (item (mean (select imgs 0 i)))))]
             [p (in-list (hash-ref j 'means))]
             [i (in-naturals)])
         (check-= r p tol (format "cifar10 fixture mean ~a" i))))
     (let ()
       (define j (python-check "creation_kwargs.py"))
       (manual-seed! 0)
       (define n64 (randn 2 2 #:dtype 'float64))
       (manual-seed! 0)
       (define n32 (randn 2 2))
       (define r64 (rand 3 #:dtype 'float64))
       (for ([pair (in-list (list (cons n64 'randn64) (cons n32 'randn32)
                                  (cons r64 'rand64)))])
         (for ([a (in-list (tensor->list (car pair)))]
               [b (in-list (hash-ref j (cdr pair)))]
               [i (in-naturals)])
           (check-= a b tol (format "~a parity ~a" (cdr pair) i))))
       (check-equal? (tensor->repr (arange 5 #:dtype 'int64))
                     (hash-ref j 'arange_int_repr))
       (check-equal? (tensor->repr (arange 2 7 #:dtype 'int64))
                     (hash-ref j 'arange_range_int_repr))
       (check-equal? (tensor->repr (arange 0 1 0.25))
                     (hash-ref j 'arange_float_repr))
       (check-equal? (tensor->repr (eye 2 #:dtype 'int64))
                     (hash-ref j 'eye_int_repr))
       (check-equal? (tensor->repr (eye 2 3)) (hash-ref j 'eye_rect_repr))
       (check-equal? (requires-grad? (zeros 2 #:requires-grad? #t))
                     (hash-ref j 'zeros_requires_grad))
       (define x (zeros 2 2))
       (check-equal? (tensor->list (full-like x 3)) (hash-ref j 'full_like))
       (check-equal? (format "torch.~a" (tensor-dtype (full-like x 3 #:dtype 'int64)))
                     (hash-ref j 'full_like_dtype))
       (check-equal? (format "torch.~a" (tensor-dtype (randn-like n64)))
                     (hash-ref j 'randn_like_dtype))
       (check-equal? (tensor-shape (randn-like n64))
                     (hash-ref j 'randn_like_shape)))
     (let ()
       (define j (python-check "bytes_ingestion.py"))
       (define t (tensor #"\0\1\2\377"))
       (check-equal? (tensor->list t) (hash-ref j 'values))
       (check-equal? (format "torch.~a" (tensor-dtype t)) (hash-ref j 'dtype))
       (check-equal? (tensor->repr t) (hash-ref j 'repr))
       (check-equal? (tensor->repr (reshape t 2 2)) (hash-ref j 'repr_2x2))
       (check-equal? (tensor->repr (tensor #"")) (hash-ref j 'empty_repr))
       (check-equal? (tensor->repr
                      (tensor (apply bytes-append
                                     (make-list 5 (list->bytes (range 256))))))
                     (hash-ref j 'summarized_repr))
       (check-equal? (tensor->list
                      (div (to (tensor (list->bytes (range 256))) 'float32)
                           255.0))
                     (hash-ref j 'scaled))
       (check-equal? (format "torch.~a" (tensor-dtype (to t 'int64)))
                     (hash-ref j 'as_int64_dtype))
       (check-equal? (tensor->repr (to (tensor '((1.5 -2.0) (0.0 3.25)))
                                       'float64))
                     (hash-ref j 'float64_repr))
       (check-equal? (item (tensor #"\7")) (hash-ref j 'item)))
     (let ()
       ;; build on CPU, move, then train — Adam created before the move
       (define (train-on device)
         (manual-seed! 0)
         (define model (Sequential (Linear 4 8) relu (Linear 8 1)))
         (define xs0 (randn 16 4))
         (define ys0 (matmul xs0 (ones 4 1)))
         (define opt (adam (parameters model) #:lr 0.1))
         (to model device)
         (define xs (to xs0 device))
         (define ys (to ys0 device))
         (define losses
           (for/list ([_ (in-range 3)])
             (zero-grads! opt)
             (define loss (mse-loss (model xs) ys))
             (backward! loss)
             (step! opt)
             (item loss)))
         (to model 'cpu)
         (values losses (append-map tensor->list (parameters model))))
       (define (check-move-twin device dev-tol)
         (define j
           (call-with-python-env
            #:env (list (cons "RKTORCH_PARITY_DEVICE" (symbol->string device)))
            (lambda () (python-check "to_move_train.py"))))
         (define-values (losses params) (train-on device))
         (for ([r (in-list losses)] [p (in-list (hash-ref j 'losses))]
               [i (in-naturals)])
           (check-= r p dev-tol (format "to_move_train[~a]: loss ~a" device i)))
         (for ([r (in-list params)] [p (in-list (hash-ref j 'params))]
               [i (in-naturals)])
           (check-= r p dev-tol
                    (format "to_move_train[~a]: parameter ~a" device i))))
       (check-move-twin 'cpu tol)
       (when (and (cuda-available?) (python-cuda-available?))
         (check-move-twin 'cuda 1e-3)))]))
