#lang racket/base

(module+ test
  (require rackunit
           "../main.rkt")

  (test-case "selection family: take/gather/take-along-dim/where (#73)"
    (define t (reshape (arange 6) 2 3))
    (check-equal? (tensor->list (take t '(0 5 3))) '(0.0 5.0 3.0))
    (check-equal? (tensor->list (take t '#(5 0))) '(5.0 0.0))
    (check-equal? (take '(1 2 3) 2) '(1 2))
    (check-equal? (tensor->list
                   (gather t 1 (to-dtype (tensor '((0 2) (1 0))) 'int64)))
                  '(0.0 2.0 4.0 3.0))
    (check-equal? (tensor->list
                   (take-along-dim t (to-dtype (tensor '((0) (2))) 'int64) 1))
                  '(0.0 5.0))
    (check-equal? (tensor->list
                   (take-along-dim t (to-dtype (tensor '(5 0)) 'int64)))
                  '(5.0 0.0))
    (check-equal? (map tensor->list (where (gt t 2.0)))
                  '((1 1 1) (0 1 2)))
    (check-equal? (tensor->list (where (gt t 2.0) t -1)) '(-1.0 -1.0 -1.0 3.0 4.0 5.0))
    (check-equal? (tensor->list (where (gt t 2.0) t (zeros 2 3)))
                  '(0.0 0.0 0.0 3.0 4.0 5.0))
    (check-equal? (tensor->list (where (gt t 2.0) -1 t))
                  '(0.0 1.0 2.0 -1.0 -1.0 -1.0))
    (let ([it (tensor '(1 2))])
      (check-equal? (tensor->list (where (eq it 1) (add1 (expt 2 53)) it))
                    (list (add1 (expt 2 53)) 2))
      (check-equal? (dtype (where (eq it 1) 7 it)) 'int64))
    (check-equal? (dtype (where (gt t 2.0) 1 0)) 'int64)
    (check-equal? (tensor->list (where (gt t 2.0) 1 0)) '(0 0 0 1 1 1))
    (check-equal? (tensor->list (where (gt t 2.0) 1.5 0.5))
                  '(0.5 0.5 0.5 1.5 1.5 1.5))
    (check-equal? (tensor->list (where (gt t 2.0) (add1 (expt 2 53)) 0))
                  (list 0 0 0 (add1 (expt 2 53)) (add1 (expt 2 53))
                        (add1 (expt 2 53))))
    (check-equal? (tensor->list
                   (index-select t 1 (to-dtype (tensor '(2 0)) 'int64)))
                  '(2.0 0.0 5.0 3.0))
    (check-equal? (tensor->list (masked-select t (gt t 3.0))) '(4.0 5.0))
    (check-equal? (shape (nonzero (gt t 0.0))) '(5 2))
    (let ([it (tensor '((1 2) (3 4)))])
      (check-equal? (dtype (where (eq it 1) it (add1 (expt 2 53)))) 'int64)
      (check-equal? (tensor->list (where (eq it 1) it (add1 (expt 2 53))))
                    (list 1 (add1 (expt 2 53)) (add1 (expt 2 53))
                          (add1 (expt 2 53)))))
    (let ([m (ne (tensor '(1 0 1)) 0)])
      (check-equal? (dtype (where m m 2)) 'int64)
      (check-equal? (tensor->list (where m m (add1 (expt 2 53))))
                    (list 1 (add1 (expt 2 53)) 1)))
    (check-equal? (tensor->list (car (where (gt (tensor 1) 0)))) '(0))
    (check-equal? (tensor->list (car (where (gt (tensor 0) 0)))) '())
    (check-exn exn:fail:contract? (lambda () (take t 2)))
    (check-exn exn:fail:contract? (lambda () (take t (gt t 2.0))))
    (check-equal? (shape (take t '())) '(0))
    (check-exn exn:fail:contract? (lambda () (masked-select t t)))
    (check-exn exn:fail:contract?
               (lambda () (gather t 1 (tensor '((0.5 1.0))))))
    (check-exn exn:fail:contract?
               (lambda () (index-select t 0 (tensor '(0.5)))))
    (check-exn exn:fail:contract?
               (lambda () (index-select t 0 (to-dtype (tensor '((0 1)))
                                                     'int64))))
    (check-exn exn:fail:contract?
               (lambda () (take-along-dim t (tensor '(1.0)))))
    (check-exn exn:fail:contract?
               (lambda () (gather t 1 (to-dtype (tensor '(0 1)) 'int64))))
    (check-exn exn:fail:contract?
               (lambda () (gather (zeros 2 3) 1 (to-dtype (zeros 3 1)
                                                          'int64))))
    (check-equal? (shape (gather (zeros 2 3) 1 (to-dtype (zeros 3 0)
                                                         'int64)))
                  '(3 0))
    (check-equal? (tensor->list (index-select (arange 3) 0 (tensor 1)))
                  '(1.0))
    (check-exn exn:fail:contract?
               (lambda ()
                 (take-along-dim t (to-dtype (tensor '(0 1)) 'int64) 1)))
    (check-exn exn:fail:contract? (lambda () (where (tensor '(1 0)))))
    (check-exn exn:fail:contract? (lambda () (where (tensor '(1 0)) t 0)))
    (check-exn exn:fail:contract? (lambda () (gather t 1 '(0 1)))))


  (test-case "indexed writes: ref! sugar and the in-place family (#73)"
    (define (fresh) (tensor '((1.0 2.0 3.0) (4.0 5.0 6.0))))
    (let ([t (fresh)])
      (ref! t 0 1 99)
      (check-equal? (tensor->list t) '(1.0 99.0 3.0 4.0 5.0 6.0)))
    (let ([t (fresh)])
      (ref! t : 0 (tensor '(7.0 8.0)))
      (check-equal? (tensor->list t) '(7.0 2.0 3.0 8.0 5.0 6.0)))
    (let ([t (fresh)])
      (ref! t (:~ 1) (: _ _ 2) 0)
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 0.0 5.0 0.0)))
    (let ([t (fresh)])
      (ref! t (gt t 4.0) -1)
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 4.0 -1.0 -1.0)))
    (let ([t (fresh)])
      (ref! t (gt t 4.0) (tensor '(9.0 10.0)))
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 4.0 9.0 10.0)))
    (let ([t (fresh)])
      (ref! t 0 .. (tensor '(9.0 9.0 9.0)))
      (check-equal? (tensor->list t) '(9.0 9.0 9.0 4.0 5.0 6.0)))
    ;; int64 write targets keep exactness through the tensor route
    (let ([it (tensor '((1 2) (3 4)))])
      (ref! it 0 1 (add1 (expt 2 53)))
      (check-equal? (tensor->list it)
                    (list 1 (add1 (expt 2 53)) 3 4)))
    (let ([t (fresh)])
      (masked-fill! t (gt t 5.0) 0)
      (index-fill! t 0 (to-dtype (tensor '(1)) 'int64) 8)
      (index-copy! t 0 (to-dtype (tensor '(0)) 'int64)
                   (tensor '((9.0 9.0 9.0))))
      (index-add! t 0 (to-dtype (tensor '(0)) 'int64)
                  (tensor '((1.0 1.0 1.0))) #:alpha 2)
      (scatter! t 1 (to-dtype (tensor '((0) (2))) 'int64) 5)
      (scatter-add! t 1 (to-dtype (tensor '((0) (0))) 'int64)
                    (tensor '((1.0) (1.0))))
      (masked-scatter! t (gt t 100.0) (tensor '(0.0)))
      (check-equal? (tensor->list t) '(6.0 11.0 11.0 9.0 8.0 5.0)))
    (check-exn exn:fail:contract?
               (lambda () (masked-fill! (fresh) (fresh) 0)))
    (check-exn exn:fail:contract?
               (lambda () (scatter! (fresh) 1 (to-dtype (tensor '(0))
                                                        'int64) 5)))
    (check-exn exn:fail:contract?
               (lambda () (index-fill! (fresh) 0 (tensor '(0.5)) 1)))
    (check-exn #rx"index_put_"
               (lambda () (tensor-ref! (fresh) 0 '(0 1))))
    ;; exact-int fills stay exact on integral destinations (2^53+1
    ;; dies in any double transit)
    (let ([it (tensor '((1 2) (3 4)))])
      (index-fill! it 0 (to-dtype (tensor '(0)) 'int64) (add1 (expt 2 53)))
      (check-equal? (take (tensor->list it) 2)
                    (list (add1 (expt 2 53)) (add1 (expt 2 53)))))
    (let ([it (tensor '(1 2 3))])
      (masked-fill! it (eq it 2) (add1 (expt 2 53)))
      (check-equal? (tensor->list it) (list 1 (add1 (expt 2 53)) 3)))
    (let ([it (tensor '((1 2) (3 4)))])
      (scatter! it 1 (to-dtype (tensor '((0) (1))) 'int64)
                (add1 (expt 2 53)))
      (check-equal? (tensor->list it)
                    (list (add1 (expt 2 53)) 2 3 (add1 (expt 2 53)))))
    ;; float64 destination keeps double precision through fill_
    (let ([d (to-dtype (zeros 1) 'float64)])
      (ref! d 0 1.0000000000000002)
      (check-equal? (tensor->list d) '(1.0000000000000002)))
    ;; 0-d targets are writable
    (let ([z (tensor 5.0)])
      (ref! z .. 7)
      (check-equal? (tensor->list (reshape z 1)) '(7.0)))
    ;; python's mask-write validation: leading-dims shape, 0-d source
    ;; broadcasts, sized source must match the true count
    (check-exn #rx"mask shape"
               (lambda () (ref! (fresh) (ne (tensor '(1 0 1)) 0) 0)))
    (let ([t (fresh)])
      (ref! t (gt t 4.0) (tensor 0.0))
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 4.0 0.0 0.0)))
    (check-exn #rx"out of range"
               (lambda () (ref! (arange 3) 3 9)))
    (check-exn #rx"out of range"
               (lambda () (ref! (arange 3) -4 9)))
    (check-exn #rx"too many indices"
               (lambda () (ref! (tensor 5.0) : 7)))
    (let ([b (gt (arange 3) 0.5)])
      (scatter! b 0 (to-dtype (tensor '(0)) 'int64) 1)
      (masked-fill! b (eq (arange 3) 1.0) 0)
      (index-fill! b 0 (to-dtype (tensor '(2)) 'int64) 1)
      (check-equal? (tensor->list b) '(1.0 0.0 1.0)))
    (check-exn #rx"true mask positions"
               (lambda ()
                 (let ([t (fresh)])
                   (ref! t (gt t 4.0) (tensor '(1.0 2.0 3.0))))))
    ;; leading-dims masks select rows, not right-aligned columns
    (let ([t (fresh)])
      (ref! t (ne (tensor '(1 0)) 0) 0)
      (check-equal? (tensor->list t) '(0.0 0.0 0.0 4.0 5.0 6.0)))
    (let ([sq (tensor '((1.0 2.0) (3.0 4.0)))])
      (ref! sq (ne (tensor '(1 0)) 0) 9)
      (check-equal? (tensor->list sq) '(9.0 9.0 3.0 4.0)))
    (let ([t (fresh)])
      (ref! t (ne (tensor '(0 1)) 0) (tensor '(7.0 8.0 9.0)))
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 7.0 8.0 9.0)))
    (let ([t (fresh)])
      (ref! t (ne (tensor '(1 0)) 0) (tensor 9.0))
      (check-equal? (tensor->list t) '(9.0 9.0 9.0 4.0 5.0 6.0)))
    (check-exn #rx"true mask positions"
               (lambda ()
                 (ref! (fresh) (ne (tensor '(1 0)) 0)
                       (tensor '(7.0 8.0)))))
    ;; #:alpha keeps exactness on int64 destinations
    (let ([it (tensor '(0 0))])
      (index-add! it 0 (to-dtype (tensor '(1)) 'int64) (tensor '(1))
                  #:alpha (add1 (expt 2 53)))
      (check-equal? (tensor->list it) (list 0 (add1 (expt 2 53)))))
    ;; broadcastable sources expand to the true positions like python
    (let ([t (fresh)])
      (ref! t (gt t 4.0) (tensor '(9.0)))
      (check-equal? (tensor->list t) '(1.0 2.0 3.0 4.0 9.0 9.0)))
    (let ([t (fresh)])
      (ref! t (ne (tensor '(1 0)) 0) (tensor '(7.0)))
      (check-equal? (tensor->list t) '(7.0 7.0 7.0 4.0 5.0 6.0)))
    (let ([sq (tensor '((1.0 2.0) (3.0 4.0)))])
      (ref! sq (ne (tensor '(1 1)) 0) (tensor '((7.0) (8.0))))
      (check-equal? (tensor->list sq) '(7.0 7.0 8.0 8.0)))
    (check-exn #rx"true mask positions"
               (lambda ()
                 (let ([t (fresh)])
                   (ref! t (gt t 4.0) (tensor '((9.0) (10.0)))))))
    (let ([it (tensor '((1 2) (3 4)))])
      (scatter! it 1 (to-dtype (tensor '((0) (1))) 'int64) 7)
      (check-equal? (tensor->list it) '(7 2 3 7)))
    (let ([it (tensor '(1 2))])
      (index-add! it 0 (to-dtype (tensor '(0)) 'int64) (tensor '(3))
                  #:alpha 2)
      (check-equal? (tensor->list it) '(7 2))))
)
