// @generated by codegen (python3 -m codegen); DO NOT EDIT.
// Schema: codegen/aten/native_functions.yaml (libtorch 2.9.0).

#pragma once

#include "torchrkt/c_api/generated/compare.h"
#include "torchrkt/c_api/generated/conv.h"
#include "torchrkt/c_api/generated/inplace.h"
#include "torchrkt/c_api/generated/linalg.h"
#include "torchrkt/c_api/generated/loss.h"
#include "torchrkt/c_api/generated/math.h"
#include "torchrkt/c_api/generated/nn.h"
#include "torchrkt/c_api/generated/reduce.h"
#include "torchrkt/c_api/generated/shape.h"
